// 全 310 種寶可夢特性庫 (繁體中文版)
window.ABILITIES_DB = [
  { id: "001", name: "惡臭", en: "Stench", desc: "通過釋放臭臭的氣味，在攻擊的時候，有時會使對手畏縮。" },
  { id: "002", name: "降雨", en: "Drizzle", desc: "出場時，會將天氣變為下雨。" },
  { id: "003", name: "加速", en: "Speed Boost", desc: "每一回合速度會變快。" },
  { id: "004", name: "戰鬥盔甲", en: "Battle Armor", desc: "被堅硬的甲殼守護著，不會被對手的攻擊擊中要害。" },
  { id: "005", name: "結實", en: "Sturdy", desc: "在ＨＰ全滿時，即使受到招式攻擊，也不會被一擊打倒。一擊必殺的招式也沒有效果。" },
  { id: "006", name: "濕氣", en: "Damp", desc: "通過把周圍都弄濕，使誰都無法使用自爆等爆炸類的招式。" },
  { id: "007", name: "柔軟", en: "Limber", desc: "因為身體柔軟，不會變為麻痺狀態。" },
  { id: "008", name: "沙隱", en: "Sand Veil", desc: "在沙暴的時候，閃避率會提高。" },
  { id: "009", name: "靜電", en: "Static", desc: "身上帶有靜電，有時會讓接觸到的對手麻痺。" },
  { id: "010", name: "蓄電", en: "Volt Absorb", desc: "受到電屬性的招式攻擊時，不會受到傷害，而是會回復。" },
  { id: "011", name: "儲水", en: "Water Absorb", desc: "受到水屬性的招式攻擊時，不會受到傷害，而是會回復。" },
  { id: "012", name: "遲鈍", en: "Oblivious", desc: "因為感覺遲鈍，不會變為著迷和被挑釁狀態。對威嚇也毫不動搖。" },
  { id: "013", name: "無關天氣", en: "Cloud Nine", desc: "任何天氣的影響都會消失。" },
  { id: "014", name: "複眼", en: "Compound Eyes", desc: "因為擁有複眼，招式的命中率會提高。" },
  { id: "015", name: "不眠", en: "Insomnia", desc: "因為有著睡不著的體質，所以不會陷入睡眠狀態。" },
  { id: "016", name: "變色", en: "Color Change", desc: "自己的屬性會變為從對手處所受招式的屬性。" },
  { id: "017", name: "免疫", en: "Immunity", desc: "因為體內擁有免疫能力，不會變為中毒狀態。" },
  { id: "018", name: "引火", en: "Flash Fire", desc: "受到火屬性的招式攻擊時，吸收火焰，自己使出的火屬性招式會變強。" },
  { id: "019", name: "鱗粉", en: "Shield Dust", desc: "被鱗粉守護著，不會受到招式的追加效果影響。" },
  { id: "020", name: "我行我素", en: "Own Tempo", desc: "因為我行我素，不會變為混亂狀態。對威嚇也毫不動搖。" },
  { id: "021", name: "吸盤", en: "Suction Cups", desc: "用吸盤牢牢貼在地面上，讓替換寶可夢的招式和道具無效。" },
  { id: "022", name: "威嚇", en: "Intimidate", desc: "出場時威嚇對手，讓其退縮，降低對手的攻擊。" },
  { id: "023", name: "踩影", en: "Shadow Tag", desc: "踩住對手的影子使其無法逃走或替換。" },
  { id: "024", name: "粗糙皮膚", en: "Rough Skin", desc: "受到攻擊時，用粗糙的皮膚弄傷接觸到自己的對手。" },
  { id: "025", name: "神奇守護", en: "Wonder Guard", desc: "不可思議的力量，只有效果絕佳的招式才能擊中。" },
  { id: "026", name: "飄浮", en: "Levitate", desc: "從地面浮起，從而不會受到地面屬性招式的攻擊。" },
  { id: "027", name: "孢子", en: "Effect Spore", desc: "受到攻擊時，有時會把接觸到自己的對手變為中毒、麻痺或睡眠狀態。" },
  { id: "028", name: "同步", en: "Synchronize", desc: "將自己的中毒、麻痺或灼傷狀態傳染給對手。" },
  { id: "029", name: "恆淨之軀", en: "Clear Body", desc: "不會因為對手的招式或特性而被降低能力。" },
  { id: "030", name: "自然回復", en: "Natural Cure", desc: "回到同行隊伍後，異常狀態就會被治癒。" },
  { id: "031", name: "避雷針", en: "Lightning Rod", desc: "將電屬性的招式吸引到自己身上，不會受到傷害，而是會提高特攻。" },
  { id: "032", name: "天恩", en: "Serene Grace", desc: "托天恩的福，招式的追加效果容易出現。" },
  { id: "033", name: "悠游自如", en: "Swift Swim", desc: "下雨天氣時，速度會提高。" },
  { id: "034", name: "葉綠素", en: "Chlorophyll", desc: "晴朗天氣時，速度會提高。" },
  { id: "035", name: "發光", en: "Illuminate", desc: "通過讓周圍變亮來保持命中率不會被降低。" },
  { id: "036", name: "複製", en: "Trace", desc: "出場時，複製對手的特性，變為與之相同的特性。" },
  { id: "037", name: "大力士", en: "Huge Power", desc: "物理攻擊的威力會變為２倍。" },
  { id: "038", name: "毒刺", en: "Poison Point", desc: "有時會讓接觸到自己的對手變為中毒狀態。" },
  { id: "039", name: "精神力", en: "Inner Focus", desc: "擁有經過鍛鍊的精神，而不會因對手的攻擊而畏縮。對威嚇也毫不動搖。" },
  { id: "040", name: "熔岩鎧甲", en: "Magma Armor", desc: "將熾熱的熔岩覆蓋在身上，不會變為冰凍狀態。" },
  { id: "041", name: "水幕", en: "Water Veil", desc: "將水幕裹在身上，不會變為灼傷狀態。" },
  { id: "042", name: "磁力", en: "Magnet Pull", desc: "用磁力吸住鋼屬性的寶可夢，使其無法逃走。" },
  { id: "043", name: "隔音", en: "Soundproof", desc: "通過屏蔽聲音，不受到聲音招式的影響。" },
  { id: "044", name: "雨盤", en: "Rain Dish", desc: "下雨天氣時，會緩緩回復ＨＰ。" },
  { id: "045", name: "揚沙", en: "Sand Stream", desc: "出場時，會把天氣變為沙暴。" },
  { id: "046", name: "壓迫感", en: "Pressure", desc: "給予對手壓迫感，大量減少其使用招式的ＰＰ。" },
  { id: "047", name: "厚脂肪", en: "Thick Fat", desc: "因為被厚厚的脂肪保護著，會讓火屬性和冰屬性的招式傷害減半。" },
  { id: "048", name: "早起", en: "Early Bird", desc: "即使變為睡眠狀態，也能以２倍的速度提早醒來。" },
  { id: "049", name: "火焰之軀", en: "Flame Body", desc: "有時會讓接觸到自己的對手變為灼傷狀態。" },
  { id: "050", name: "逃跑", en: "Run Away", desc: "一定能從野生寶可夢那兒逃走。" },
  { id: "051", name: "銳利目光", en: "Keen Eye", desc: "多虧了銳利的目光，命中率不會被降低。" },
  { id: "052", name: "怪力鉗", en: "Hyper Cutter", desc: "因為擁有以力量自豪的鉗子，不會被對手降低攻擊。" },
  { id: "053", name: "撿拾", en: "Pickup", desc: "有時會撿來對手用過的道具，冒險過程中也會撿到。" },
  { id: "054", name: "懶惰", en: "Truant", desc: "如果使出招式，下一回合就會休息。" },
  { id: "055", name: "活力", en: "Hustle", desc: "自己的攻擊變高，但命中率會降低。" },
  { id: "056", name: "迷人之軀", en: "Cute Charm", desc: "有時會讓接觸到自己的對手著迷。" },
  { id: "057", name: "正電", en: "Plus", desc: "出場的夥伴之間如果有正電或負電特性的寶可夢，自己的特攻會提高。" },
  { id: "058", name: "負電", en: "Minus", desc: "出場的夥伴之間如果有正電或負電特性的寶可夢，自己的特攻會提高。" },
  { id: "059", name: "陰晴不定", en: "Forecast", desc: "受天氣的影響，會變為水屬性、火屬性或冰屬性中的某一個。" },
  { id: "060", name: "黏著", en: "Sticky Hold", desc: "因為道具是粘在黏性身體上的，所以不會被對手奪走。" },
  { id: "061", name: "蛻皮", en: "Shed Skin", desc: "通過蛻去身上的皮，有時會治癒異常狀態。" },
  { id: "062", name: "毅力", en: "Guts", desc: "如果變為異常狀態，會拿出毅力，攻擊會提高。" },
  { id: "063", name: "神奇鱗片", en: "Marvel Scale", desc: "如果變為異常狀態，神奇鱗片會發生反應，防禦會提高。" },
  { id: "064", name: "污泥漿", en: "Liquid Ooze", desc: "吸收了污泥漿的對手會因強烈的惡臭而受到傷害，減少ＨＰ。" },
  { id: "065", name: "茂盛", en: "Overgrow", desc: "ＨＰ減少的時候，草屬性的招式威力會提高。" },
  { id: "066", name: "猛火", en: "Blaze", desc: "ＨＰ減少的時候，火屬性的招式威力會提高。" },
  { id: "067", name: "激流", en: "Torrent", desc: "ＨＰ減少的時候，水屬性的招式威力會提高。" },
  { id: "068", name: "蟲之預感", en: "Swarm", desc: "ＨＰ減少的時候，蟲屬性的招式威力會提高。" },
  { id: "069", name: "堅硬腦袋", en: "Rock Head", desc: "即使使出會受反作用力傷害的招式，ＨＰ也不會減少。" },
  { id: "070", name: "日照", en: "Drought", desc: "出場時，會將天氣變為晴朗。" },
  { id: "071", name: "沙穴", en: "Arena Trap", desc: "在戰鬥中讓對手無法逃走。" },
  { id: "072", name: "干勁", en: "Vital Spirit", desc: "通過激發出干勁，不會變為睡眠狀態。" },
  { id: "073", name: "白色煙霧", en: "White Smoke", desc: "被白色煙霧保護著，不會被對手降低能力。" },
  { id: "074", name: "瑜伽之力", en: "Pure Power", desc: "因瑜伽的力量，物理攻擊的威力會變為２倍。" },
  { id: "075", name: "硬殼盔甲", en: "Shell Armor", desc: "被堅硬的殼保護著，對手的攻擊不會擊中要害。" },
  { id: "076", name: "氣閘", en: "Air Lock", desc: "所有天氣的影響都會消失。" },
  { id: "077", name: "蹣跚", en: "Tangled Feet", desc: "在混亂狀態時，閃避率會提高。" },
  { id: "078", name: "電氣引擎", en: "Motor Drive", desc: "受到電屬性的招式攻擊時，不會受到傷害，而是速度會提高。" },
  { id: "079", name: "鬥爭心", en: "Rivalry", desc: "面對性別相同的對手，會燃起鬥爭心，變得更強。而面對性別不同的，則會變弱。" },
  { id: "080", name: "不屈之心", en: "Steadfast", desc: "每次畏縮時，不屈之心就會燃起，速度也會提高。" },
  { id: "081", name: "雪隱", en: "Snow Cloak", desc: "下雪天氣時，閃避率會提高。" },
  { id: "082", name: "貪吃鬼", en: "Gluttony", desc: "原本ＨＰ變得很少時才會吃樹果，在ＨＰ還有一半時就會把它吃掉。" },
  { id: "083", name: "憤怒穴位", en: "Anger Point", desc: "要害被擊中時，會大發雷霆，攻擊力變為最大。" },
  { id: "084", name: "輕裝", en: "Unburden", desc: "失去所持有的道具時，速度會提高。" },
  { id: "085", name: "耐熱", en: "Heatproof", desc: "耐熱的體質會讓火屬性的招式傷害減半。" },
  { id: "086", name: "單純", en: "Simple", desc: "能力變化會變為平時的２倍。" },
  { id: "087", name: "乾燥皮膚", en: "Dry Skin", desc: "下雨天氣時和受到水屬性的招式時，ＨＰ會回復。晴朗天氣時和受到火屬性的招式時，ＨＰ會減少。" },
  { id: "088", name: "下載", en: "Download", desc: "比較對手的防禦和特防，根據較低的那項能力相應地提高自己的攻擊或特攻。" },
  { id: "089", name: "鐵拳", en: "Iron Fist", desc: "使用拳類招式的威力會提高。" },
  { id: "090", name: "毒療", en: "Poison Heal", desc: "變為中毒狀態時，ＨＰ不會減少，反而會增加起來。" },
  { id: "091", name: "適應力", en: "Adaptability", desc: "與自身同屬性的招式威力會提高。" },
  { id: "092", name: "連續攻擊", en: "Skill Link", desc: "如果使用連續招式，總是能使出最高次數。" },
  { id: "093", name: "濕潤之軀", en: "Hydration", desc: "下雨天氣時，異常狀態會治癒。" },
  { id: "094", name: "太陽之力", en: "Solar Power", desc: "晴朗天氣時，特攻會提高，而每回合ＨＰ會減少。" },
  { id: "095", name: "飛毛腿", en: "Quick Feet", desc: "變為異常狀態時，速度會提高。" },
  { id: "096", name: "一般皮膚", en: "Normalize", desc: "無論是什麼屬性的招式，全部會變為一般屬性。威力會少量提高。" },
  { id: "097", name: "狙擊手", en: "Sniper", desc: "擊中要害時，威力會變得更強。" },
  { id: "098", name: "魔法防守", en: "Magic Guard", desc: "不會受到攻擊以外的傷害。" },
  { id: "099", name: "無防守", en: "No Guard", desc: "由於無防守戰術，雙方使出的招式都必定會擊中。" },
  { id: "100", name: "慢出", en: "Stall", desc: "使出招式的順序必定會變為最後。" },
  { id: "101", name: "技術高手", en: "Technician", desc: "攻擊時可以將低威力招式的威力提高。" },
  { id: "102", name: "葉子防守", en: "Leaf Guard", desc: "晴朗天氣時，不會變為異常狀態。" },
  { id: "103", name: "笨拙", en: "Klutz", desc: "無法使用持有的道具。" },
  { id: "104", name: "破格", en: "Mold Breaker", desc: "可以不受對手特性的干擾，向對手使出招式。" },
  { id: "105", name: "超幸運", en: "Super Luck", desc: "因為擁有超幸運，攻擊容易擊中對手的要害。" },
  { id: "106", name: "引爆", en: "Aftermath", desc: "變為瀕死時，會對接觸到自己的對手造成傷害。" },
  { id: "107", name: "危險預知", en: "Anticipation", desc: "可以察覺到對手擁有的危險招式。" },
  { id: "108", name: "預知夢", en: "Forewarn", desc: "出場時，只讀取１個對手擁有的招式。" },
  { id: "109", name: "純樸", en: "Unaware", desc: "可以無視對手能力的變化，進行攻擊。" },
  { id: "110", name: "有色眼鏡", en: "Tinted Lens", desc: "可以將效果不好的招式以通常的威力使出。" },
  { id: "111", name: "過濾", en: "Filter", desc: "受到效果絕佳的攻擊時，可以減弱其威力。" },
  { id: "112", name: "慢啟動", en: "Slow Start", desc: "在５回合內，攻擊和速度減半。" },
  { id: "113", name: "膽量", en: "Scrappy", desc: "一般屬性和格鬥屬性的招式可以擊中幽靈屬性的寶可夢。對威嚇也毫不動搖。" },
  { id: "114", name: "引水", en: "Storm Drain", desc: "將水屬性的招式引到自己身上，不會受到傷害，而是會提高特攻。" },
  { id: "115", name: "冰凍之軀", en: "Ice Body", desc: "下雪天氣時，會緩緩回復ＨＰ。" },
  { id: "116", name: "堅硬岩石", en: "Solid Rock", desc: "受到效果絕佳的攻擊時，可以減弱其威力。" },
  { id: "117", name: "降雪", en: "Snow Warning", desc: "出場時，會將天氣變為下雪。" },
  { id: "118", name: "採蜜", en: "Honey Gather", desc: "戰鬥結束時，有時候會撿來甜甜蜜。" },
  { id: "119", name: "察覺", en: "Frisk", desc: "出場時，可以察覺對手的持有物。" },
  { id: "120", name: "捨身", en: "Reckless", desc: "自己會因反作用力受傷的招式，其威力會提高。" },
  { id: "121", name: "多屬性", en: "Multitype", desc: "自己的屬性會根據持有的石板而改變。" },
  { id: "122", name: "花之禮", en: "Flower Gift", desc: "晴朗天氣時，自己與同伴的攻擊和特防能力會提高。" },
  { id: "123", name: "夢魘", en: "Bad Dreams", desc: "給予睡眠狀態的對手傷害。" },
  { id: "124", name: "順手牽羊", en: "Pickpocket", desc: "盜取接觸到自己的對手的道具。" },
  { id: "125", name: "強行", en: "Sheer Force", desc: "招式的追加效果消失，但因此能以更高的威力使出招式。" },
  { id: "126", name: "唱反調", en: "Contrary", desc: "能力的變化發生逆轉，原本提高時會降低，而原本降低時會提高。" },
  { id: "127", name: "緊張感", en: "Unnerve", desc: "讓對手緊張，使其無法食用樹果。" },
  { id: "128", name: "不服輸", en: "Defiant", desc: "被對手降低能力時，攻擊會大幅提高。" },
  { id: "129", name: "軟弱", en: "Defeatist", desc: "ＨＰ減半時，會變得軟弱，攻擊和特攻會減半。" },
  { id: "130", name: "詛咒之軀", en: "Cursed Body", desc: "受到攻擊時，有時會把對手的招式變為定身法狀態。" },
  { id: "131", name: "治癒之心", en: "Healer", desc: "有時會治癒異常狀態的同伴。" },
  { id: "132", name: "友情防守", en: "Friend Guard", desc: "可以減少我方的傷害。" },
  { id: "133", name: "碎裂鎧甲", en: "Weak Armor", desc: "受到物理招式的傷害時，防禦會降低，速度會大幅提高。" },
  { id: "134", name: "重金屬", en: "Heavy Metal", desc: "自身的重量會變為２倍。" },
  { id: "135", name: "輕金屬", en: "Light Metal", desc: "自身的重量會減半。" },
  { id: "136", name: "多重鱗片", en: "Multiscale", desc: "ＨＰ全滿時，受到的傷害會變少。" },
  { id: "137", name: "中毒激升", en: "Toxic Boost", desc: "變為中毒狀態時，物理招式的威力會提高。" },
  { id: "138", name: "受熱激升", en: "Flare Boost", desc: "變為灼傷狀態時，特殊招式的威力會提高。" },
  { id: "139", name: "收穫", en: "Harvest", desc: "可以多次製作出已被使用掉的樹果。" },
  { id: "140", name: "心電感應", en: "Telepathy", desc: "讀取我方的攻擊，並閃避其招式傷害。" },
  { id: "141", name: "心情不定", en: "Moody", desc: "每一回合，能力中的某項會大幅提高，而某項會降低。" },
  { id: "142", name: "防塵", en: "Overcoat", desc: "不會受到沙暴的傷害。也不會受到粉末類和孢子類招式的影響。" },
  { id: "143", name: "毒手", en: "Poison Touch", desc: "只通過接觸就有可能讓對手變為中毒狀態。" },
  { id: "144", name: "再生力", en: "Regenerator", desc: "退回同行隊伍後，ＨＰ會少量回復。" },
  { id: "145", name: "健壯胸肌", en: "Big Pecks", desc: "不會受到防禦降低的效果。" },
  { id: "146", name: "撥沙", en: "Sand Rush", desc: "沙暴天氣時，速度會提高。" },
  { id: "147", name: "奇蹟皮膚", en: "Wonder Skin", desc: "成為不易受到變化招式攻擊的身體。" },
  { id: "148", name: "分析", en: "Analytic", desc: "如果在最後使出招式，招式的威力會提高。" },
  { id: "149", name: "幻覺", en: "Illusion", desc: "假扮成同行隊伍中的最後一隻寶可夢出場，迷惑對手。" },
  { id: "150", name: "變身者", en: "Imposter", desc: "變身為當前遇見的寶可夢。" },
  { id: "151", name: "穿透", en: "Infiltrator", desc: "可以穿透對手的壁障或替身進行攻擊。" },
  { id: "152", name: "木乃伊", en: "Mummy", desc: "被對手接觸到後，會將對手變為木乃伊。" },
  { id: "153", name: "自信過度", en: "Moxie", desc: "如果打倒對手，就會充滿自信，攻擊會提高。" },
  { id: "154", name: "正義之心", en: "Justified", desc: "受到惡屬性的招式攻擊時，因為正義感，攻擊會提高。" },
  { id: "155", name: "膽怯", en: "Rattled", desc: "受到惡屬性、幽靈屬性和蟲屬性的攻擊或威嚇時，會因膽怯而速度提高。" },
  { id: "156", name: "魔法鏡", en: "Magic Bounce", desc: "可以不受到由對手使出的變化招式影響，並將其反彈。" },
  { id: "157", name: "食草", en: "Sap Sipper", desc: "受到草屬性的招式攻擊時，不會受到傷害，而是攻擊會提高。" },
  { id: "158", name: "惡作劇之心", en: "Prankster", desc: "可以率先使出變化招式。" },
  { id: "159", name: "沙之力", en: "Sand Force", desc: "沙暴天氣時，岩石屬性、地面屬性和鋼屬性的招式威力會提高。" },
  { id: "160", name: "鐵刺", en: "Iron Barbs", desc: "用鐵刺給予接觸到自己的對手傷害。" },
  { id: "161", name: "達摩模式", en: "Zen Mode", desc: "ＨＰ變為一半以下時，樣子會改變。" },
  { id: "162", name: "勝利之星", en: "Victory Star", desc: "自己和同伴的命中率會提高。" },
  { id: "163", name: "渦輪火焰", en: "Turboblaze", desc: "可以不受對手特性的干擾，向對手使出招式。" },
  { id: "164", name: "兆級電壓", en: "Teravolt", desc: "可以不受對手特性的干擾，向對手使出招式。" },
  { id: "165", name: "芳香幕", en: "Aroma Veil", desc: "可以防住向自己和同伴發出的心靈攻擊。" },
  { id: "166", name: "花幕", en: "Flower Veil", desc: "我方的草屬性寶可夢能力不會降低，也不會變為異常狀態。" },
  { id: "167", name: "頰囊", en: "Cheek Pouch", desc: "無論是哪種樹果，食用後，ＨＰ都會回復。" },
  { id: "168", name: "變幻自如", en: "Protean", desc: "變為與自己使出的招式相同的屬性。每次出場戰鬥僅生效一次。" },
  { id: "169", name: "毛皮大衣", en: "Fur Coat", desc: "對手給予的物理招式的傷害會減半。" },
  { id: "170", name: "魔術師", en: "Magician", desc: "奪走被自己的招式擊中的對手的道具。" },
  { id: "171", name: "防彈", en: "Bulletproof", desc: "可以防住對手的球和彈類招式。" },
  { id: "172", name: "好勝", en: "Competitive", desc: "如果被對手降低能力，特攻會大幅提高。" },
  { id: "173", name: "強壯之顎", en: "Strong Jaw", desc: "因為顎部強壯，啃咬類招式的威力會提高。" },
  { id: "174", name: "冰凍皮膚", en: "Refrigerate", desc: "一般屬性的招式會變為冰屬性。威力會少量提高。" },
  { id: "175", name: "甜幕", en: "Sweet Veil", desc: "自己和同伴的寶可夢不會變為睡眠狀態。" },
  { id: "176", name: "戰鬥切換", en: "Stance Change", desc: "如果使出攻擊招式，會變為刀劍形態，如果使出招式「王者盾牌」，會變為盾牌形態。" },
  { id: "177", name: "疾風之翼", en: "Gale Wings", desc: "ＨＰ全滿時，飛行屬性的招式可以率先使出。" },
  { id: "178", name: "超級發射器", en: "Mega Launcher", desc: "波動和波導類招式的威力會提高。" },
  { id: "179", name: "草之毛皮", en: "Grass Pelt", desc: "在青草場地時，防禦會提高。" },
  { id: "180", name: "共生", en: "Symbiosis", desc: "同伴使用道具時，會把自己持有的道具傳遞給同伴。" },
  { id: "181", name: "硬爪", en: "Tough Claws", desc: "接觸到對手的招式威力會提高。" },
  { id: "182", name: "妖精皮膚", en: "Pixilate", desc: "一般屬性的招式會變為妖精屬性。威力會少量提高。" },
  { id: "183", name: "黏滑", en: "Gooey", desc: "對於用攻擊接觸到自己的對手，會降低其速度。" },
  { id: "184", name: "飛行皮膚", en: "Aerilate", desc: "一般屬性的招式會變為飛行屬性。威力會少量提高。" },
  { id: "185", name: "親子愛", en: "Parental Bond", desc: "親子倆可以合計攻擊２次。" },
  { id: "186", name: "暗黑氣場", en: "Dark Aura", desc: "全體的惡屬性招式變強。" },
  { id: "187", name: "妖精氣場", en: "Fairy Aura", desc: "全體的妖精屬性招式變強。" },
  { id: "188", name: "氣場破壞", en: "Aura Break", desc: "讓氣場的效果發生逆轉，降低威力。" },
  { id: "189", name: "始源之海", en: "Primordial Sea", desc: "變為不會受到火屬性攻擊的天氣。" },
  { id: "190", name: "終結之地", en: "Desolate Land", desc: "變為不會受到水屬性攻擊的天氣。" },
  { id: "191", name: "德爾塔氣流", en: "Delta Stream", desc: "變為令飛行屬性的弱點消失的天氣。" },
  { id: "192", name: "持久力", en: "Stamina", desc: "受到攻擊時，防禦會提高。" },
  { id: "193", name: "躍躍欲逃", en: "Wimp Out", desc: "ＨＰ變為一半時，會慌慌張張逃走，退回同行隊伍中。" },
  { id: "194", name: "危險回避", en: "Emergency Exit", desc: "ＨＰ變為一半時，為了迴避危險，會退回到同行隊伍中。" },
  { id: "195", name: "遇水凝固", en: "Water Compaction", desc: "受到水屬性的招式攻擊時，防禦會大幅提高。" },
  { id: "196", name: "不仁不義", en: "Merciless", desc: "攻擊中毒狀態的對手時，必定會擊中要害。" },
  { id: "197", name: "界限盾殼", en: "Shields Down", desc: "ＨＰ變為一半時，殼會壞掉，變得有攻擊性。" },
  { id: "198", name: "蹲守", en: "Stakeout", desc: "可以對替換出場的對手以２倍的傷害進行攻擊。" },
  { id: "199", name: "水泡", en: "Water Bubble", desc: "降低自己受到的火屬性招式的威力，不會灼傷。" },
  { id: "200", name: "鋼能力者", en: "Steelworker", desc: "鋼屬性的招式威力會提高。" },
  { id: "201", name: "怒火沖天", en: "Berserk", desc: "因對手的攻擊ＨＰ變為一半時，特攻會提高。" },
  { id: "202", name: "撥雪", en: "Slush Rush", desc: "下雪天氣時，速度會提高。" },
  { id: "203", name: "遠隔", en: "Long Reach", desc: "可以不接觸對手就使出所有的招式。" },
  { id: "204", name: "濕潤之聲", en: "Liquid Voice", desc: "所有的聲音招式都變為水屬性。" },
  { id: "205", name: "先行治療", en: "Triage", desc: "可以率先使出回復招式。" },
  { id: "206", name: "電氣皮膚", en: "Galvanize", desc: "一般屬性的招式會變為電屬性。威力會少量提高。" },
  { id: "207", name: "衝浪之尾", en: "Surge Surfer", desc: "電氣場地時，速度會變為２倍。" },
  { id: "208", name: "魚群", en: "Schooling", desc: "ＨＰ多的時候會聚起來變強。ＨＰ剩餘量變少時，群體會分崩離析。" },
  { id: "209", name: "畫皮", en: "Disguise", desc: "通過畫皮覆蓋住身體，可以防住１次攻擊。" },
  { id: "210", name: "牽絆變身", en: "Battle Bond", desc: "打倒對手時，與訓練家的牽絆會增強，自己的攻擊、特攻、速度會提高。" },
  { id: "211", name: "群聚變形", en: "Power Construct", desc: "ＨＰ變為一半時，細胞們會趕來支援，變為完全體形態。" },
  { id: "212", name: "腐蝕", en: "Corrosion", desc: "可以使鋼屬性和毒屬性的寶可夢也陷入中毒狀態。" },
  { id: "213", name: "絕對睡眠", en: "Comatose", desc: "總是半夢半醒的狀態，絕對不會醒來。可以就這麼睡著進行攻擊。" },
  { id: "214", name: "女王的威嚴", en: "Queenly Majesty", desc: "向對手施加威懾力，使其無法對我方使出先制招式。" },
  { id: "215", name: "飛出的內在物", en: "Innards Out", desc: "被對手打倒的時候，會給予對手相當於ＨＰ剩餘量的傷害。" },
  { id: "216", name: "舞者", en: "Dancer", desc: "有誰使出跳舞招式時，自己也能就這麼接著使出跳舞招式。" },
  { id: "217", name: "蓄電池", en: "Battery", desc: "會提高我方的特殊招式的威力。" },
  { id: "218", name: "毛茸茸", en: "Fluffy", desc: "會將對手所給予的接觸類招式的傷害減半，但火屬性招式的傷害會變為２倍。" },
  { id: "219", name: "鮮艷之軀", en: "Dazzling", desc: "讓對手嚇一跳，使其無法對我方使出先制招式。" },
  { id: "220", name: "魂心", en: "Soul-Heart", desc: "寶可夢每次變為瀕死狀態時，特攻會提高。" },
  { id: "221", name: "捲髮", en: "Tangling Hair", desc: "對於用攻擊接觸到自己的對手，會降低其速度。" },
  { id: "222", name: "接球手", en: "Receiver", desc: "繼承被打倒的同伴的特性，變為相同的特性。" },
  { id: "223", name: "化學之力", en: "Power of Alchemy", desc: "繼承被打倒的同伴的特性，變為相同的特性。" },
  { id: "224", name: "異獸提升", en: "Beast Boost", desc: "打倒對手的時候，自己最高的那項能力會提高。" },
  { id: "225", name: "ＡＲ系統", en: "RKS System", desc: "根據持有的存儲碟，自己的屬性會改變。" },
  { id: "226", name: "電氣製造者", en: "Electric Surge", desc: "出場時，會佈下電氣場地。" },
  { id: "227", name: "精神製造者", en: "Psychic Surge", desc: "出場時，會佈下精神場地。" },
  { id: "228", name: "薄霧製造者", en: "Misty Surge", desc: "出場時，會佈下薄霧場地。" },
  { id: "229", name: "青草製造者", en: "Grassy Surge", desc: "出場時，會佈下青草場地。" },
  { id: "230", name: "金屬防護", en: "Full Metal Body", desc: "不會因為對手的招式或特性而被降低能力。" },
  { id: "231", name: "幻影防守", en: "Shadow Shield", desc: "ＨＰ全滿時，受到的傷害會變少。" },
  { id: "232", name: "稜鏡裝甲", en: "Prism Armor", desc: "受到效果絕佳的攻擊時，可以減弱其威力。" },
  { id: "233", name: "腦核之力", en: "Neuroforce", desc: "效果絕佳的攻擊，威力會變得更強。" },
  { id: "234", name: "不撓之劍", en: "Intrepid Sword", desc: "首次出場時，攻擊會提高。" },
  { id: "235", name: "不屈之盾", en: "Dauntless Shield", desc: "首次出場時，防禦會提高。" },
  { id: "236", name: "自由者", en: "Libero", desc: "變為與自己使出的招式相同的屬性。每次出場戰鬥僅生效一次。" },
  { id: "237", name: "撿球", en: "Ball Fetch", desc: "沒有攜帶道具時，會拾取第１個投出後捕捉失敗的精靈球。" },
  { id: "238", name: "棉絮", en: "Cotton Down", desc: "受到攻擊後撒下棉絮，降低除自己以外的所有寶可夢的速度。" },
  { id: "239", name: "螺旋尾鰭", en: "Propeller Tail", desc: "能無視具有吸引對手招式效果的特性或招式的影響。" },
  { id: "240", name: "鏡甲", en: "Mirror Armor", desc: "只反彈自己受到的能力降低效果。" },
  { id: "241", name: "一口飛彈", en: "Gulp Missile", desc: "衝浪或潛水時會叼來獵物。受到傷害時，會吐出獵物進行攻擊。" },
  { id: "242", name: "堅毅", en: "Stalwart", desc: "能無視具有吸引對手招式效果的特性或招式的影響。" },
  { id: "243", name: "蒸汽機", en: "Steam Engine", desc: "受到水屬性或火屬性的招式攻擊時，速度會巨幅提高。" },
  { id: "244", name: "龐克搖滾", en: "Punk Rock", desc: "聲音招式的威力會提高。受到的聲音招式傷害會減半。" },
  { id: "245", name: "吐沙", en: "Sand Spit", desc: "受到攻擊時，會刮起沙暴。" },
  { id: "246", name: "冰鱗粉", en: "Ice Scales", desc: "由於有冰鱗粉的守護，受到的特殊攻擊傷害會減半。" },
  { id: "247", name: "熟成", en: "Ripen", desc: "使樹果成熟，效果變為２倍。" },
  { id: "248", name: "結凍頭", en: "Ice Face", desc: "頭部的冰會代替自己承受物理攻擊，但是樣子會改變。下雪時，冰會恢復原狀。" },
  { id: "249", name: "能量點", en: "Power Spot", desc: "只要處在相鄰位置，招式的威力就會提高。" },
  { id: "250", name: "擬態", en: "Mimicry", desc: "寶可夢的屬性會根據場地的狀態而變化。" },
  { id: "251", name: "除障", en: "Screen Cleaner", desc: "出場時，敵方和我方的光牆、反射壁和極光幕的效果會消失。" },
  { id: "252", name: "鋼之意志", en: "Steely Spirit", desc: "我方的鋼屬性攻擊威力會提高。" },
  { id: "253", name: "滅亡之軀", en: "Perish Body", desc: "受到接觸類招式攻擊時，雙方都會在３回合後變為瀕死狀態。替換後效果消失。" },
  { id: "254", name: "遊魂", en: "Wandering Spirit", desc: "與使用接觸類招式攻擊自己的寶可夢互換特性。" },
  { id: "255", name: "一猩一意", en: "Gorilla Tactics", desc: "雖然攻擊會提高，但是只能使出一開始所選的招式。" },
  { id: "256", name: "化學變化氣體", en: "Neutralizing Gas", desc: "特性為化學變化氣體的寶可夢在場時，場上所有寶可夢的特性效果都會消失或者無法生效。" },
  { id: "257", name: "粉彩護幕", en: "Pastel Veil", desc: "自己和同伴都不會陷入中毒的異常狀態。" },
  { id: "258", name: "飽了又餓", en: "Hunger Switch", desc: "每回合結束時會在滿腹花紋與空腹花紋之間交替改變樣子。" },
  { id: "259", name: "速擊", en: "Quick Draw", desc: "有時能比對手先一步行動。" },
  { id: "260", name: "無形拳", en: "Unseen Fist", desc: "如果使出的是接觸到對手的招式，就可以無視守護效果進行攻擊。" },
  { id: "261", name: "怪藥", en: "Curious Medicine", desc: "出場時會從貝殼撒藥，將我方的能力變化復原。" },
  { id: "262", name: "電晶體", en: "Transistor", desc: "電屬性的招式威力會提高。" },
  { id: "263", name: "龍顎", en: "Dragon's Maw", desc: "龍屬性的招式威力會提高。" },
  { id: "264", name: "蒼白嘶鳴", en: "Chilling Neigh", desc: "打倒對手時會用冰冷的聲音嘶鳴並提高攻擊。" },
  { id: "265", name: "漆黑嘶鳴", en: "Grim Neigh", desc: "打倒對手時會用恐怖的聲音嘶鳴並提高特攻。" },
  { id: "266", name: "人馬一體", en: "As One", desc: "兼備蕾冠王的緊張感和雪暴馬的蒼白嘶鳴這兩種特性。" },
  { id: "267", name: "人馬一體", en: "As One", desc: "兼備蕾冠王的緊張感和靈幽馬的漆黑嘶鳴這兩種特性。" },
  { id: "268", name: "甩不掉的氣味", en: "Lingering Aroma", desc: "被對手接觸到後，甩不掉的氣味會沾上對手。" },
  { id: "269", name: "掉出種子", en: "Seed Sower", desc: "受到攻擊時，會將腳下變成青草場地。" },
  { id: "270", name: "熱交換", en: "Thermal Exchange", desc: "受到火屬性的招式攻擊時，攻擊會提高，且不會陷入灼傷狀態。" },
  { id: "271", name: "憤怒甲殼", en: "Anger Shell", desc: "因被對手攻擊而ＨＰ變為一半時，會因憤怒降低防禦和特防。但攻擊、特攻、速度會提高。" },
  { id: "272", name: "潔淨之鹽", en: "Purifying Salt", desc: "因潔淨的鹽而不會陷入異常狀態。會讓幽靈屬性的招式傷害減半。" },
  { id: "273", name: "焦香之軀", en: "Well-Baked Body", desc: "受到火屬性的招式攻擊時，不會受到傷害，而是會大幅提高防禦。" },
  { id: "274", name: "乘風", en: "Wind Rider", desc: "吹起了順風或受到風的招式攻擊時，不會受到傷害，而是會提高攻擊。" },
  { id: "275", name: "看門犬", en: "Guard Dog", desc: "受到威嚇時，攻擊會提高。讓替換寶可夢的招式和道具無效。" },
  { id: "276", name: "搬岩", en: "Rocky Payload", desc: "岩石屬性的招式威力會提高。" },
  { id: "277", name: "風力發電", en: "Wind Power", desc: "受到風的招式攻擊時，會變為充電狀態。" },
  { id: "278", name: "全能變身", en: "Zero to Hero", desc: "回到同行隊伍後，會變為全能形態。" },
  { id: "279", name: "發號施令", en: "Commander", desc: "出場時，若我方當中有吃吼霸，就會進入其口中，並從其口中發出指令。" },
  { id: "280", name: "電力轉換", en: "Electromorphosis", desc: "受到傷害時，會變為充電狀態。" },
  { id: "281", name: "古代活性", en: "Protosynthesis", desc: "攜帶著驅勁能量或天氣為晴朗時，數值最高的能力會提高。" },
  { id: "282", name: "夸克充能", en: "Quark Drive", desc: "攜帶著驅勁能量或在電氣場地上時，數值最高的能力會提高。" },
  { id: "283", name: "黃金之軀", en: "Good as Gold", desc: "不會氧化的堅固黃金身軀不會受到對手的變化招式的影響。" },
  { id: "284", name: "災禍之鼎", en: "Vessel of Ruin", desc: "以能呼喚災厄的鼎的力量降低除自己以外的寶可夢的特攻。" },
  { id: "285", name: "災禍之劍", en: "Sword of Ruin", desc: "以能呼喚災厄的劍的力量降低除自己以外的寶可夢的防禦。" },
  { id: "286", name: "災禍之簡", en: "Tablets of Ruin", desc: "以能呼喚災厄的簡的力量降低除自己以外的寶可夢的攻擊。" },
  { id: "287", name: "災禍之玉", en: "Beads of Ruin", desc: "以能呼喚災厄的勾玉的力量降低除自己以外的寶可夢的特防。" },
  { id: "288", name: "緋紅脈動", en: "Orichalcum Pulse", desc: "出場時，會將天氣變為晴朗。日照強烈時，會通過古代的脈動升高攻擊。" },
  { id: "289", name: "強子引擎", en: "Hadron Engine", desc: "出場時，會佈下電氣場地。處於電氣場地時，會通過未來的機關升高特攻。" },
  { id: "290", name: "跟風", en: "Opportunist", desc: "對手的能力提高時，自己也會趁機同樣地提高能力。" },
  { id: "291", name: "反芻", en: "Cud Chew", desc: "吃了樹果後，會在下一回合結束時從胃反芻出來再吃１次。" },
  { id: "292", name: "鋒銳", en: "Sharpness", desc: "提高切割對手的招式的威力。" },
  { id: "293", name: "大將", en: "Supreme Overlord", desc: "出場時，攻擊和特攻會按照目前被打倒的同伴數量逐漸提升，被打倒越多，提升越多。" },
  { id: "294", name: "同台共演", en: "Costar", desc: "出場時，複製同伴的能力變化。" },
  { id: "295", name: "毒滿地", en: "Toxic Debris", desc: "受到物理招式的傷害時，會在對手腳下散佈毒菱。" },
  { id: "296", name: "尾甲", en: "Armor Tail", desc: "包裹頭部的神秘尾巴使對手無法對我方使出先制招式。" },
  { id: "297", name: "食土", en: "Earth Eater", desc: "受到地面屬性的招式攻擊時，不會受到傷害，而是會得到回復。" },
  { id: "298", name: "菌絲之力", en: "Mycelium Might", desc: "使出變化招式時，雖然行動必定會變慢，但能不受對手的特性妨礙。" },
  { id: "299", name: "款待", en: "Hospitality", desc: "出場時款待同伴，回復其少量ＨＰ。" },
  { id: "300", name: "心眼", en: "Mind's Eye", desc: "一般屬性和格鬥屬性的招式可以擊中幽靈屬性的寶可夢。無視對手的閃避率的變化，且命中率不會被降低。" },
  { id: "301", name: "面影輝映", en: "Embody Aspect", desc: "將回憶映於心中，讓碧草面具發出光輝，提高自己的速度。" },
  { id: "302", name: "面影輝映", en: "Embody Aspect", desc: "將回憶映於心中，讓火灶面具發出光輝，提高自己的攻擊。" },
  { id: "303", name: "面影輝映", en: "Embody Aspect", desc: "將回憶映於心中，讓水井面具發出光輝，提高自己的特防。" },
  { id: "304", name: "面影輝映", en: "Embody Aspect", desc: "將回憶映於心中，讓礎石面具發出光輝，提高自己的防禦。" },
  { id: "305", name: "毒鎖鏈", en: "Toxic Chain", desc: "憑藉含有毒素的鎖鏈的力量，有時能讓被招式擊中的對手陷入劇毒狀態。" },
  { id: "306", name: "甘露之蜜", en: "Supersweet Syrup", desc: "首次出場時，會散發出甜膩的蜜的香味來降低對手的閃避率。" },
  { id: "307", name: "太晶變形", en: "Tera Shift", desc: "出場時，會吸收周圍的能量，變為太晶形態。" },
  { id: "308", name: "太晶甲殼", en: "Tera Shell", desc: "甲殼蘊藏著全部屬性的力量，會將自己ＨＰ全滿時受到的傷害全都變為效果不好。" },
  { id: "309", name: "歸零化境", en: "Teraform Zero", desc: "太樂巴戈斯變為星晶形態時，蘊藏在牠身上的力量會將天氣和場地的影響全部歸零。" },
  { id: "310", name: "毒傀儡", en: "Poison Puppeteer", desc: "因桃歹郎的招式而陷入中毒狀態的對手同時也會陷入混亂狀態。" }
];
