// 🍓 樹果 (生果類)[cite: 12]
window.BERRY_ITEMS = [
  { id: "Cheri Berry", name: "櫻子果", en: "Cheri Berry", desc: "讓寶可夢攜帶後，可以治癒麻痺。" }, //[cite: 12]
  { id: "Chesto Berry", name: "零餘果", en: "Chesto Berry", desc: "讓寶可夢攜帶後，可以治癒睡眠。" }, //[cite: 12]
  { id: "Pecha Berry", name: "桃桃果", en: "Pecha Berry", desc: "讓寶可夢攜帶後，可以治癒中毒。" }, //[cite: 12]
  { id: "Rawst Berry", name: "莓莓果", en: "Rawst Berry", desc: "讓寶可夢攜帶後，可以治癒灼傷。" }, //[cite: 12]
  { id: "Aspear Berry", name: "利木果", en: "Aspear Berry", desc: "讓寶可夢攜帶後，可以治癒冰凍。" }, //[cite: 12]
  { id: "Oran Berry", name: "橙橙果", en: "Oran Berry", desc: "讓寶可夢攜帶後，可以回復１０ＨＰ。" }, //[cite: 12]
  { id: "Persim Berry", name: "柿仔果", en: "Persim Berry", desc: "讓寶可夢攜帶後，可以治癒混亂。" }, //[cite: 12]
  { id: "Lum Berry", name: "木子果", en: "Lum Berry", desc: "讓寶可夢攜帶後，可以治癒所有異常狀態。" }, //[cite: 12]
  { id: "Sitrus Berry", name: "文柚果", en: "Sitrus Berry", desc: "讓寶可夢攜帶後，可以回復少量ＨＰ。" }, //[cite: 12]
  { id: "Figy Berry", name: "勿花果", en: "Figy Berry", desc: "讓寶可夢攜帶後，危機時可以回復ＨＰ。如果討厭這味道就會混亂。" }, //[cite: 12]
  { id: "Wiki Berry", name: "異奇果", en: "Wiki Berry", desc: "讓寶可夢攜帶後，危機時可以回復ＨＰ。如果討厭這味道就會混亂。" }, //[cite: 12]
  { id: "Mago Berry", name: "芒芒果", en: "Mago Berry", desc: "讓寶可夢攜帶後，危機時可以回復ＨＰ。如果討厭這味道就會混亂。" }, //[cite: 12]
  { id: "Aguav Berry", name: "樂芭果", en: "Aguav Berry", desc: "讓寶可夢攜帶後，危機時可以回復ＨＰ。如果討厭這味道就會混亂。" }, //[cite: 12]
  { id: "Iapapa Berry", name: "芭亞果", en: "Iapapa Berry", desc: "讓寶可夢攜帶後，危機時可以回復ＨＰ。如果討厭這味道就會混亂。" }, //[cite: 12]
  // 抗性減半果[cite: 12]
  { id: "Occa Berry", name: "巧可果", en: "Occa Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的火屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Passho Berry", name: "千香果", en: "Passho Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的水屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Wacan Berry", name: "燭木果", en: "Wacan Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的電屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Rindo Berry", name: "羅子果", en: "Rindo Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的草屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Yache Berry", name: "番荔果", en: "Yache Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的冰屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Chople Berry", name: "蓮蒲果", en: "Chople Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的格鬥屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Kebia Berry", name: "通通果", en: "Kebia Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的毒屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Shuca Berry", name: "腰木果", en: "Shuca Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的地面屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Coba Berry", name: "棱瓜果", en: "Coba Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的飛行屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Payapa Berry", name: "福祿果", en: "Payapa Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的超能力屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Tanga Berry", name: "扁櫻果", en: "Tanga Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的蟲屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Charti Berry", name: "草蠶果", en: "Charti Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的岩石屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Kasib Berry", name: "佛柑果", en: "Kasib Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的幽靈屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Haban Berry", name: "哈密果", en: "Haban Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的龍屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Colbur Berry", name: "刺角果", en: "Colbur Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的惡屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Babiri Berry", name: "霹靂果", en: "Babiri Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的鋼屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  { id: "Roseli Berry", name: "洛玫果", en: "Roseli Berry", desc: "讓寶可夢攜帶後，在受到效果絕佳的妖精屬性招式攻擊時，能令其威力減弱。" }, //[cite: 12]
  // 危機提升能力果[cite: 12]
  { id: "Liechi Berry", name: "枝荔果", en: "Liechi Berry", desc: "讓寶可夢攜帶後，危機時，自己的攻擊就會提高。" }, //[cite: 12]
  { id: "Ganlon Berry", name: "龍睛果", en: "Ganlon Berry", desc: "讓寶可夢攜帶後，危機時，自己的防禦就會提高。" }, //[cite: 12]
  { id: "Salac Berry", name: "沙鱗果", en: "Salac Berry", desc: "讓寶可夢攜帶後，危機時，自己的速度就會提高。" }, //[cite: 12]
  { id: "Petaya Berry", name: "龍火果", en: "Petaya Berry", desc: "讓寶可夢攜帶後，危機時，自己的特攻就會提高。" }, //[cite: 12]
  { id: "Apicot Berry", name: "杏仔果", en: "Apicot Berry", desc: "讓寶可夢攜帶後，危機時，自己的特防就會提高。" }, //[cite: 12]
  { id: "Lansat Berry", name: "蘭薩果", en: "Lansat Berry", desc: "讓寶可夢攜帶後，危機時，攻擊會變得容易擊中要害。" }, //[cite: 12]
  { id: "Starf Berry", name: "星桃果", en: "Starf Berry", desc: "讓寶可夢攜帶後，危機時，某一項能力就會大幅提高。" }, //[cite: 12]
  { id: "Micle Berry", name: "奇秘果", en: "Micle Berry", desc: "讓寶可夢攜帶後，危機時，招式的命中率僅會提高１次。" }, //[cite: 12]
  { id: "Custap Berry", name: "釋陀果", en: "Custap Berry", desc: "讓寶可夢攜帶後，危機時，行動僅會變快１次。" }, //[cite: 12]
  { id: "Jaboca Berry", name: "嘉珍果", en: "Jaboca Berry", desc: "讓寶可夢攜帶後，在受到物理招式攻擊時，能給予對手傷害。" }, //[cite: 12]
  { id: "Rowap Berry", name: "霧蓮果", en: "Rowap Berry", desc: "讓寶可夢攜帶後，在受到特殊招式攻擊時，能給予對手傷害。" }, //[cite: 12]
  { id: "Kee Berry", name: "亞開果", en: "Kee Berry", desc: "讓寶可夢攜帶後，在受到物理招式攻擊時，自己的防禦就會提高。" }, //[cite: 12]
  { id: "Maranga Berry", name: "香羅果", en: "Maranga Berry", desc: "讓寶可夢攜帶後，在受到特殊招式攻擊時，自己的特防就會提高。" } //[cite: 12]
];

// ⚔️ 對戰攜帶道具 (其餘類)[cite: 12]
window.BATTLE_ITEMS = [
  { id: "None", name: "(無攜帶道具)", en: "None", desc: "無任何加成" },
  // 核心輸出/增傷道具[cite: 12]
  { id: "Choice Band", name: "講究頭帶", en: "Choice Band", desc: "有點講究的頭帶。雖然攜帶後攻擊會提高，但只能使出相同的招式。" }, //[cite: 12]
  { id: "Choice Specs", name: "講究眼鏡", en: "Choice Specs", desc: "有點講究的眼鏡。雖然攜帶後特攻會提高，但只能使出相同的招式。" }, //[cite: 12]
  { id: "Choice Scarf", name: "講究圍巾", en: "Choice Scarf", desc: "有點講究的圍巾。雖然攜帶後速度會提高，但只能使出相同的招式。" }, //[cite: 12]
  { id: "Life Orb", name: "生命寶珠", en: "Life Orb", desc: "攜帶後，雖然每次攻擊時ＨＰ少量減少，但招式的威力會提高。" }, //[cite: 12]
  { id: "Expert Belt", name: "達人帶", en: "Expert Belt", desc: "用慣了的黑色帶子。攜帶後，效果絕佳時的招式威力就會少量提高。" }, //[cite: 12]
  { id: "Booster Energy", name: "驅勁能量", en: "Booster Energy", desc: "充滿能量的膠囊。讓有某種特性的寶可夢攜帶後，其能力會得到提升。" }, //[cite: 12]
  
  // 防禦/抗性/生存道具[cite: 12]
  { id: "Assault Vest", name: "突擊背心", en: "Assault Vest", desc: "會變得富有攻擊性的背心。雖然攜帶後特防會提高，但會無法使出變化招式。" }, //[cite: 12]
  { id: "Focus Sash", name: "氣勢披帶", en: "Focus Sash", desc: "攜帶後，在ＨＰ全滿時，即便受到可能會導致瀕死的招式，也能僅以１ＨＰ撐過去１次。" }, //[cite: 12]
  { id: "Eviolite", name: "進化奇石", en: "Eviolite", desc: "進化的神奇石塊。攜帶後，還能進化的寶可夢的防禦和特防就會提高。" }, //[cite: 12]
  { id: "Leftovers", name: "吃剩的東西", en: "Leftovers", desc: "攜帶後，寶可夢的ＨＰ會在戰鬥期間緩緩回復。" }, //[cite: 12]
  { id: "Black Sludge", name: "黑色污泥", en: "Black Sludge", desc: "攜帶後，毒屬性的寶可夢會緩緩回復ＨＰ。其他屬性的話，ＨＰ則會減少。" }, //[cite: 12]
  { id: "Rocky Helmet", name: "凸凸頭盔", en: "Rocky Helmet", desc: "讓寶可夢攜帶後，在受到打擊招式攻擊時，能給予對手傷害。" }, //[cite: 12]
  
  // 功能與戰術道具[cite: 12]
  { id: "Clear Amulet", name: "清淨墜飾", en: "Clear Amulet", desc: "光芒晶瑩剔透的墜飾。攜帶後，不會因為對手的招式或特性而被降低能力。" }, //[cite: 12]
  { id: "Covert Cloak", name: "密探斗篷", en: "Covert Cloak", desc: "攜帶後，能夠隱藏身體，變得不會受到招式的追加效果影響。" }, //[cite: 12]
  { id: "Safety Goggles", name: "防塵護目鏡", en: "Safety Goggles", desc: "不單是天氣造成的傷害，連粉末類招式的效果也能防禦的護目鏡。" }, //[cite: 12]
  { id: "Loaded Dice", name: "機變骰子", en: "Loaded Dice", desc: "只會出現好數字的骰子。攜帶後，在使用連續招式時，能使出較多次招式。" }, //[cite: 12]
  { id: "Weakness Policy", name: "弱點保險", en: "Weakness Policy", desc: "被針對弱點時，攻擊和特攻就會大幅提高。" }, //[cite: 12]
  { id: "Blunder Policy", name: "打空保險", en: "Blunder Policy", desc: "招式因命中率影響而落空時，速度會大幅提高。" }, //[cite: 12]
  { id: "Air Balloon", name: "氣球", en: "Air Balloon", desc: "讓寶可夢攜帶後，寶可夢會浮在空中。受到攻擊就會破裂。" }, //[cite: 12]
  { id: "Eject Button", name: "逃脫按鍵", en: "Eject Button", desc: "攜帶它的寶可夢如果受到招式攻擊，就能逃脫戰鬥，並和同行的其他寶可夢進行替換。" }, //[cite: 12]
  { id: "Eject Pack", name: "避難背包", en: "Eject Pack", desc: "當攜帶它的寶可夢能力下降時，同行寶可夢就會自動替換上場。" }, //[cite: 12]
  { id: "Heavy-Duty Boots", name: "厚底靴", en: "Heavy-Duty Boots", desc: "不受腳下陷阱等影響。" }, //[cite: 12]
  { id: "Ability Shield", name: "特性護具", en: "Ability Shield", desc: "可愛而有個性的盾。攜帶後，特性不會被對手改變。" }, //[cite: 12]
  { id: "Mirror Herb", name: "模仿香草", en: "Mirror Herb", desc: "攜帶它的寶可夢僅有１次機會可以在對手提高能力時，對其進行模仿並提高同樣的能力。" }, //[cite: 12]
  { id: "Punching Glove", name: "拳擊手套", en: "Punching Glove", desc: "保護拳頭的手套。攜帶後，拳擊招式的威力會提高，且變得拳擊時不會接觸到對手。" }, //[cite: 12]

  // 場地與天氣延長道具[cite: 12]
  { id: "Light Clay", name: "光之黏土", en: "Light Clay", desc: "當攜帶它的寶可夢使出光牆或反射壁時，效果會比平時持續得更長。" }, //[cite: 12]
  { id: "Terrain Extender", name: "大地膜", en: "Terrain Extender", desc: "當攜帶它的寶可夢利用招式或特性展開場地時，場地的持續時間會比平時更長。" }, //[cite: 12]
  { id: "Icy Rock", name: "冰冷岩石", en: "Icy Rock", desc: "攜帶它的寶可夢使出冰雹/雪景時，時間會比平時更長。" }, //[cite: 12]
  { id: "Smooth Rock", name: "沙沙岩石", en: "Smooth Rock", desc: "攜帶它的寶可夢使出沙暴時，沙暴的時間會比平時更長。" }, //[cite: 12]
  { id: "Heat Rock", name: "熾熱岩石", en: "Heat Rock", desc: "攜帶它的寶可夢使出大晴天時，晴天的時間會比平時更長。" }, //[cite: 12]
  { id: "Damp Rock", name: "潮濕岩石", en: "Damp Rock", desc: "攜帶它的寶可夢使出求雨時，下雨的時間會比平時更長。" }, //[cite: 12]

  // 狀態種子[cite: 12]
  { id: "Electric Seed", name: "電氣種子", en: "Electric Seed", desc: "讓寶可夢攜帶後，在電氣場地上使用，防禦就會提高。" }, //[cite: 12]
  { id: "Psychic Seed", name: "精神種子", en: "Psychic Seed", desc: "讓寶可夢攜帶後，在精神場地上使用，特防就會提高。" }, //[cite: 12]
  { id: "Misty Seed", name: "薄霧種子", en: "Misty Seed", desc: "讓寶可夢攜帶後，在薄霧場地上使用，特防就會提高。" }, //[cite: 12]
  { id: "Grassy Seed", name: "青草種子", en: "Grassy Seed", desc: "讓寶可夢攜帶後，在青草場地上使用，防禦就會提高。" }, //[cite: 12]

  // 屬性 1.2 倍增傷道具[cite: 12]
  { id: "Spell Tag", name: "詛咒之符", en: "Spell Tag", desc: "古怪可怕的咒符。攜帶後，幽靈屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Charcoal", name: "木炭", en: "Charcoal", desc: "焚燒用的燃料。攜帶後，火屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Mystic Water", name: "神秘水滴", en: "Mystic Water", desc: "水滴形狀的寶石。攜帶後，水屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Magnet", name: "磁鐵", en: "Magnet", desc: "強力的磁鐵。攜帶後，電屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Miracle Seed", name: "奇蹟種子", en: "Miracle Seed", desc: "孕育生命的種子。攜帶後，草屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Never-Melt Ice", name: "不融冰", en: "Never-Melt Ice", desc: "能隔絕熱量的冰。攜帶後，冰屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Black Belt", name: "黑帶", en: "Black Belt", desc: "能振作精神的帶子。攜帶後，格鬥屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Poison Barb", name: "毒針", en: "Poison Barb", desc: "有毒的小針。攜帶後，毒屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Soft Sand", name: "柔軟沙子", en: "Soft Sand", desc: "手感細膩的沙子。攜帶後，地面屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Sharp Beak", name: "銳利鳥嘴", en: "Sharp Beak", desc: "又長又尖的鳥嘴。攜帶後，飛行屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Twisted Spoon", name: "彎曲的湯匙", en: "Twisted Spoon", desc: "注入了念力的湯匙。攜帶後，超能力屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Silver Powder", name: "銀粉", en: "Silver Powder", desc: "散發著銀色光輝的粉末。攜帶後，蟲屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Hard Stone", name: "硬石頭", en: "Hard Stone", desc: "絕對不會裂開的石頭。攜帶後，岩石屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Dragon Fang", name: "龍之牙", en: "Dragon Fang", desc: "堅硬銳利的牙齒。攜帶後，龍屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Black Glasses", name: "黑色眼鏡", en: "Black Glasses", desc: "看上去很奇怪的眼鏡。攜帶後，惡屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Metal Coat", name: "金屬膜", en: "Metal Coat", desc: "特殊的金屬膜。攜帶後，鋼屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Fairy Feather", name: "妖精之羽", en: "Fairy Feather", desc: "接觸到光後就會微微發光的羽毛。攜帶後，妖精屬性的招式威力就會提高。" }, //[cite: 12]
  { id: "Silk Scarf", name: "絲綢圍巾", en: "Silk Scarf", desc: "手感不錯的圍巾。攜帶後，一般屬性的招式威力就會提高。" } //[cite: 12]
];
