// 全 920 種招式資料庫 (繁體中文版 - 第 1 批: 1~150)[cite: 13]
window.MOVES_DB = window.MOVES_DB || [];
window.MOVES_DB = window.MOVES_DB.concat([
  { id: 1, name: "拍擊", en: "Pound", type: "一般", cat: "physical", bp: 40, acc: 100, pp: 35, desc: "使用長長的尾巴或手等拍打對手進行攻擊。" },
  { id: 2, name: "空手劈", en: "Karate Chop", type: "格鬥", cat: "physical", bp: 50, acc: 100, pp: 25, desc: "用鋒利的手刀劈向對手進行攻擊。容易擊中要害。" },
  { id: 3, name: "連環巴掌", en: "Double Slap", type: "一般", cat: "physical", bp: 15, acc: 85, pp: 10, desc: "用連環巴掌拍打對手進行攻擊。連續攻擊２～５次。" },
  { id: 4, name: "連續拳", en: "Comet Punch", type: "一般", cat: "physical", bp: 18, acc: 85, pp: 15, desc: "用拳頭怒濤般的毆打對手進行攻擊。連續攻擊２～５次。" },
  { id: 5, name: "百萬噸重拳", en: "Mega Punch", type: "一般", cat: "physical", bp: 80, acc: 85, pp: 20, desc: "用充滿力量的拳頭攻擊對手。" },
  { id: 6, name: "聚寶功", en: "Pay Day", type: "一般", cat: "physical", bp: 40, acc: 100, pp: 20, desc: "向對手的身體投擲小金幣進行攻擊。戰鬥後可以拿到錢。" },
  { id: 7, name: "火焰拳", en: "Fire Punch", type: "火", cat: "physical", bp: 75, acc: 100, pp: 15, desc: "用充滿火焰的拳頭攻擊對手。有時會讓對手陷入灼傷狀態。" },
  { id: 8, name: "冰凍拳", en: "Ice Punch", type: "冰", cat: "physical", bp: 75, acc: 100, pp: 15, desc: "用充滿寒氣的拳頭攻擊對手。有時會讓對手陷入冰凍狀態。" },
  { id: 9, name: "雷電拳", en: "Thunder Punch", type: "電", cat: "physical", bp: 75, acc: 100, pp: 15, desc: "用充滿電流的拳頭攻擊對手。有時會讓對手陷入麻痺狀態。" },
  { id: 10, name: "抓", en: "Scratch", type: "一般", cat: "physical", bp: 40, acc: 100, pp: 35, desc: "用堅硬且無比鋒利的爪子抓對手進行攻擊。" },
  { id: 11, name: "夾住", en: "Vise Grip", type: "一般", cat: "physical", bp: 55, acc: 100, pp: 30, desc: "將對手從兩側夾住，給予傷害。" },
  { id: 12, name: "極落鉗", en: "Guillotine", type: "一般", cat: "physical", bp: 0, acc: 0, pp: 5, desc: "用大鉗子或剪刀等夾斷對手進行攻擊。只要命中就會一擊昏厥。" },
  { id: 13, name: "旋風刀", en: "Razor Wind", type: "一般", cat: "special", bp: 80, acc: 100, pp: 10, desc: "製造風之刃，於第２回合攻擊對手。容易擊中要害。" },
  { id: 14, name: "劍舞", en: "Swords Dance", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "激烈地跳起戰舞提高氣勢。大幅提高自己的攻擊。" },
  { id: 15, name: "居合劈", en: "Cut", type: "一般", cat: "physical", bp: 50, acc: 95, pp: 30, desc: "用鐮刀或爪子等切斬對手進行攻擊。" },
  { id: 16, name: "起風", en: "Gust", type: "飛行", cat: "special", bp: 40, acc: 100, pp: 35, desc: "用翅膀將刮起的狂風襲向對手進行攻擊。" },
  { id: 17, name: "翅膀攻擊", en: "Wing Attack", type: "飛行", cat: "physical", bp: 60, acc: 100, pp: 35, desc: "大大地展開美麗的翅膀，將其撞向對手進行攻擊。" },
  { id: 18, name: "吹飛", en: "Whirlwind", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "吹飛對手，強制拉後備寶可夢上場。如果對手為野生寶可夢，戰鬥將直接結束。" },
  { id: 19, name: "飛翔", en: "Fly", type: "飛行", cat: "physical", bp: 90, acc: 95, pp: 15, desc: "第１回合飛上天空，第２回合攻擊對手。" },
  { id: 20, name: "綁緊", en: "Bind", type: "一般", cat: "physical", bp: 15, acc: 85, pp: 20, desc: "使用長長的身體或藤蔓等，在４～５回合內綁緊對手進行攻擊。" },
  { id: 21, name: "摔打", en: "Slam", type: "一般", cat: "physical", bp: 80, acc: 75, pp: 20, desc: "使用長長的尾巴或藤蔓等摔打對手進行攻擊。" },
  { id: 22, name: "藤鞭", en: "Vine Whip", type: "草", cat: "physical", bp: 45, acc: 100, pp: 25, desc: "用如同鞭子般彎曲而細長的藤蔓摔打對手進行攻擊。" },
  { id: 23, name: "踩踏", en: "Stomp", type: "一般", cat: "physical", bp: 65, acc: 100, pp: 20, desc: "用大腳踩踏對手進行攻擊。有時會使對手畏縮。" },
  { id: 24, name: "二連踢", en: "Double Kick", type: "格鬥", cat: "physical", bp: 30, acc: 100, pp: 30, desc: "用２隻腳踢飛對手進行攻擊。連續２次給予傷害。" },
  { id: 25, name: "百萬噸重踢", en: "Mega Kick", type: "一般", cat: "physical", bp: 120, acc: 75, pp: 5, desc: "使出力大無窮的重踢踢飛對手進行攻擊。" },
  { id: 26, name: "飛踢", en: "Jump Kick", type: "格鬥", cat: "physical", bp: 100, acc: 95, pp: 10, desc: "使出高高的騰空踢攻擊對手。如果踢偏則自己會受到傷害。" },
  { id: 27, name: "迴旋踢", en: "Rolling Kick", type: "格鬥", cat: "physical", bp: 60, acc: 85, pp: 15, desc: "一邊使身體快速旋轉，一邊踢飛對手進行攻擊。有時會使對手畏縮。" },
  { id: 28, name: "潑沙", en: "Sand Attack", type: "地面", cat: "status", bp: 0, acc: 100, pp: 15, desc: "向對手臉上潑沙子，從而降低命中率。" },
  { id: 29, name: "頭錘", en: "Headbutt", type: "一般", cat: "physical", bp: 70, acc: 100, pp: 15, desc: "將頭伸出，筆直地撲向對手進行攻擊。有時會使對手畏縮。" },
  { id: 30, name: "角撞", en: "Horn Attack", type: "一般", cat: "physical", bp: 65, acc: 100, pp: 25, desc: "用尖銳的角攻擊對手。" },
  { id: 31, name: "亂擊", en: "Fury Attack", type: "一般", cat: "physical", bp: 15, acc: 85, pp: 20, desc: "用角或喙刺向對手進行攻擊。連續攻擊２～５次。" },
  { id: 32, name: "角鑽", en: "Horn Drill", type: "一般", cat: "physical", bp: 0, acc: 0, pp: 5, desc: "用旋轉的角刺入對手進行攻擊。只要命中就會一擊昏厥。" },
  { id: 33, name: "撞擊", en: "Tackle", type: "一般", cat: "physical", bp: 40, acc: 100, pp: 35, desc: "用整個身體撞向對手進行攻擊。" },
  { id: 34, name: "泰山壓頂", en: "Body Slam", type: "一般", cat: "physical", bp: 85, acc: 100, pp: 15, desc: "用整個身體壓住對手進行攻擊。有時會讓對手陷入麻痺狀態。" },
  { id: 35, name: "緊束", en: "Wrap", type: "一般", cat: "physical", bp: 15, acc: 90, pp: 20, desc: "使用長長的身體或藤蔓等，在４～５回合內緊束對手進行攻擊。" },
  { id: 36, name: "猛撞", en: "Take Down", type: "一般", cat: "physical", bp: 90, acc: 85, pp: 20, desc: "以驚人的氣勢撞向對手進行攻擊。自己也會受到少許傷害。" },
  { id: 37, name: "大鬧一番", en: "Thrash", type: "一般", cat: "physical", bp: 120, acc: 100, pp: 10, desc: "在２～３回合內，亂打一氣地攻擊對手。大鬧一番後自己會陷入混亂。" },
  { id: 38, name: "捨身衝撞", en: "Double-Edge", type: "一般", cat: "physical", bp: 120, acc: 100, pp: 15, desc: "拼命地猛撞向對手進行攻擊。自己也會受到不小的傷害。" },
  { id: 39, name: "搖尾巴", en: "Tail Whip", type: "一般", cat: "status", bp: 0, acc: 100, pp: 30, desc: "可愛地左右搖晃尾巴，誘使對手疏忽大意。會降低對手的防禦。" },
  { id: 40, name: "毒針", en: "Poison Sting", type: "毒", cat: "physical", bp: 15, acc: 100, pp: 35, desc: "將有毒的針刺入對手進行攻擊。有時會讓對手陷入中毒狀態。" },
  { id: 41, name: "雙針", en: "Twineedle", type: "蟲", cat: "physical", bp: 25, acc: 100, pp: 20, desc: "將２根針刺入對手，連續２次給予傷害。有時會讓對手陷入中毒狀態。" },
  { id: 42, name: "飛彈針", en: "Pin Missile", type: "蟲", cat: "physical", bp: 25, acc: 95, pp: 20, desc: "向對手發射銳針進行攻擊。連續攻擊２～５次。" },
  { id: 43, name: "瞪眼", en: "Leer", type: "一般", cat: "status", bp: 0, acc: 100, pp: 30, desc: "用犀利的眼神使其害怕，從而降低對手的防禦。" },
  { id: 44, name: "咬住", en: "Bite", type: "惡", cat: "physical", bp: 60, acc: 100, pp: 25, desc: "用尖銳的牙咬住對手進行攻擊。有時會使對手畏縮。" },
  { id: 45, name: "叫聲", en: "Growl", type: "一般", cat: "status", bp: 0, acc: 100, pp: 40, desc: "讓對手聽可愛的叫聲，引開注意力使其疏忽，從而降低對手的攻擊。" },
  { id: 46, name: "吼叫", en: "Roar", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "放走對手，強制拉後備寶可夢上場。如果對手為野生寶可夢，戰鬥將直接結束。" },
  { id: 47, name: "唱歌", en: "Sing", type: "一般", cat: "status", bp: 0, acc: 55, pp: 15, desc: "讓對手聽舒適、美妙的歌聲，從而陷入睡眠狀態。" },
  { id: 48, name: "超音波", en: "Supersonic", type: "一般", cat: "status", bp: 0, acc: 55, pp: 20, desc: "從身體發出特殊的音波，從而使對手混亂。" },
  { id: 49, name: "音爆", en: "Sonic Boom", type: "一般", cat: "special", bp: 0, acc: 90, pp: 20, desc: "將衝擊波撞向對手進行攻擊。必定會給予20的傷害。" },
  { id: 50, name: "定身法", en: "Disable", type: "一般", cat: "status", bp: 0, acc: 100, pp: 20, desc: "阻礙對手行動，之前使出的招式將在４回合內無法使用。" },
  { id: 51, name: "溶解液", en: "Acid", type: "毒", cat: "special", bp: 40, acc: 100, pp: 30, desc: "將強酸潑向對手進行攻擊。有時會降低對手的特防。" },
  { id: 52, name: "火花", en: "Ember", type: "火", cat: "special", bp: 40, acc: 100, pp: 25, desc: "向對手發射小型火焰進行攻擊。有時會讓對手陷入灼傷狀態。" },
  { id: 53, name: "噴射火焰", en: "Flamethrower", type: "火", cat: "special", bp: 90, acc: 100, pp: 15, desc: "向對手發射烈焰進行攻擊。有時會讓對手陷入灼傷狀態。" },
  { id: 54, name: "白霧", en: "Mist", type: "冰", cat: "status", bp: 0, acc: 0, pp: 30, desc: "用白霧覆蓋身體。在５回合內不會讓對手降低自己的能力。" },
  { id: 55, name: "水槍", en: "Water Gun", type: "水", cat: "special", bp: 40, acc: 100, pp: 25, desc: "向對手猛烈地噴射水流進行攻擊。" },
  { id: 56, name: "水炮", en: "Hydro Pump", type: "水", cat: "special", bp: 110, acc: 80, pp: 5, desc: "向對手猛烈地噴射大量水流進行攻擊。" },
  { id: 57, name: "衝浪", en: "Surf", type: "水", cat: "special", bp: 90, acc: 100, pp: 15, desc: "利用大浪攻擊自己周圍所有的寶可夢。" },
  { id: 58, name: "冰凍光束", en: "Ice Beam", type: "冰", cat: "special", bp: 90, acc: 100, pp: 10, desc: "向對手發射冰凍光束進行攻擊。有時會讓對手陷入冰凍狀態。" },
  { id: 59, name: "暴風雪", en: "Blizzard", type: "冰", cat: "special", bp: 110, acc: 70, pp: 5, desc: "將猛烈的暴風雪刮向對手進行攻擊。有時會讓對手陷入冰凍狀態。" },
  { id: 60, name: "幻象光線", en: "Psybeam", type: "超能力", cat: "special", bp: 65, acc: 100, pp: 20, desc: "向對手發射神奇的光線進行攻擊。有時會使對手混亂。" },
  { id: 61, name: "泡沫光線", en: "Bubble Beam", type: "水", cat: "special", bp: 65, acc: 100, pp: 20, desc: "向對手猛烈地噴射泡沫進行攻擊。有時會降低對手的速度。" },
  { id: 62, name: "極光束", en: "Aurora Beam", type: "冰", cat: "special", bp: 65, acc: 100, pp: 20, desc: "向對手發射虹色光束進行攻擊。有時會降低對手的攻擊。" },
  { id: 63, name: "破壞光線", en: "Hyper Beam", type: "一般", cat: "special", bp: 150, acc: 90, pp: 5, desc: "向對手發射強烈的光線進行攻擊。下一回合自己將無法動彈。" },
  { id: 64, name: "啄", en: "Peck", type: "飛行", cat: "physical", bp: 35, acc: 100, pp: 35, desc: "用尖銳的喙或角刺向對手進行攻擊。" },
  { id: 65, name: "啄鑽", en: "Drill Peck", type: "飛行", cat: "physical", bp: 80, acc: 100, pp: 20, desc: "一邊旋轉，一邊將尖喙刺入對手進行攻擊。" },
  { id: 66, name: "深淵翻滾", en: "Submission", type: "格鬥", cat: "physical", bp: 80, acc: 80, pp: 20, desc: "將對手連同自己一起摔向地面進行攻擊。自己也會受到少許傷害。" },
  { id: 67, name: "踢倒", en: "Low Kick", type: "格鬥", cat: "physical", bp: 0, acc: 100, pp: 20, desc: "用力踢對手的腳，使其摔倒進行攻擊。對手越重，威力越大。" },
  { id: 68, name: "雙倍奉還", en: "Counter", type: "格鬥", cat: "physical", bp: 0, acc: 100, pp: 20, desc: "從對手那裡受到物理攻擊的傷害將以２倍返還給同一個對手。" },
  { id: 69, name: "地球上投", en: "Seismic Toss", type: "格鬥", cat: "physical", bp: 0, acc: 100, pp: 20, desc: "利用引力將對手甩飛出去。給予對手和自己等級相同的傷害。" },
  { id: 70, name: "怪力", en: "Strength", type: "一般", cat: "physical", bp: 80, acc: 100, pp: 15, desc: "使出渾身力氣毆打對手進行攻擊。" },
  { id: 71, name: "吸取", en: "Absorb", type: "草", cat: "special", bp: 20, acc: 100, pp: 25, desc: "吸取對手的養分進行攻擊。可以回復給予對手傷害的一半ＨＰ。" },
  { id: 72, name: "超級吸取", en: "Mega Drain", type: "草", cat: "special", bp: 40, acc: 100, pp: 15, desc: "吸取對手的養分進行攻擊。可以回復給予對手傷害的一半ＨＰ。" },
  { id: 73, name: "寄生種子", en: "Leech Seed", type: "草", cat: "status", bp: 0, acc: 90, pp: 10, desc: "植入寄生種子後，將在每回合一點一點吸取對手的ＨＰ，從而用來回復自己的ＨＰ。" },
  { id: 74, name: "生長", en: "Growth", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "讓身體一下子長大，從而提高攻擊和特攻。" },
  { id: 75, name: "飛葉快刀", en: "Razor Leaf", type: "草", cat: "physical", bp: 55, acc: 95, pp: 25, desc: "飛出葉片，切斬對手進行攻擊。容易擊中要害。" },
  { id: 76, name: "日光束", en: "Solar Beam", type: "草", cat: "special", bp: 120, acc: 100, pp: 10, desc: "第１回合收集滿滿的日光，第２回合發射光束進行攻擊。" },
  { id: 77, name: "毒粉", en: "Poison Powder", type: "毒", cat: "status", bp: 0, acc: 75, pp: 35, desc: "撒出毒粉，從而讓對手陷入中毒狀態。" },
  { id: 78, name: "麻痺粉", en: "Stun Spore", type: "草", cat: "status", bp: 0, acc: 75, pp: 30, desc: "撒出麻痺粉，從而讓對手陷入麻痺狀態。" },
  { id: 79, name: "催眠粉", en: "Sleep Powder", type: "草", cat: "status", bp: 0, acc: 75, pp: 15, desc: "撒出催眠粉，從而讓對手陷入睡眠狀態。" },
  { id: 80, name: "花瓣舞", en: "Petal Dance", type: "草", cat: "special", bp: 120, acc: 100, pp: 10, desc: "在２～３回合內，散落花瓣攻擊對手。之後自己會陷入混亂。" },
  { id: 81, name: "吐絲", en: "String Shot", type: "蟲", cat: "status", bp: 0, acc: 95, pp: 40, desc: "用口中吐出的絲纏繞對手，從而大幅降低對手的速度。" },
  { id: 82, name: "龍之怒", en: "Dragon Rage", type: "龍", cat: "special", bp: 0, acc: 100, pp: 10, desc: "將憤怒的衝擊波撞向對手進行攻擊。必定會給予40的傷害。" },
  { id: 83, name: "火焰旋渦", en: "Fire Spin", type: "火", cat: "special", bp: 35, acc: 85, pp: 15, desc: "將對手困在激烈的火焰旋渦中，在４～５回合內進行攻擊。" },
  { id: 84, name: "電擊", en: "Thunder Shock", type: "電", cat: "special", bp: 40, acc: 100, pp: 30, desc: "發出電流刺激對手進行攻擊。有時會讓對手陷入麻痺狀態。" },
  { id: 85, name: "十萬伏特", en: "Thunderbolt", type: "電", cat: "special", bp: 90, acc: 100, pp: 15, desc: "向對手發出強力電擊進行攻擊。有時會讓對手陷入麻痺狀態。" },
  { id: 86, name: "電磁波", en: "Thunder Wave", type: "電", cat: "status", bp: 0, acc: 90, pp: 20, desc: "向對手發出微弱的電擊，從而讓對手陷入麻痺狀態。" },
  { id: 87, name: "打雷", en: "Thunder", type: "電", cat: "special", bp: 110, acc: 70, pp: 10, desc: "向對手劈下暴雷進行攻擊。有時會讓對手陷入麻痺狀態。" },
  { id: 88, name: "落石", en: "Rock Throw", type: "岩石", cat: "physical", bp: 50, acc: 90, pp: 15, desc: "拿起小岩石，投擲對手進行攻擊。" },
  { id: 89, name: "地震", en: "Earthquake", type: "地面", cat: "physical", bp: 100, acc: 100, pp: 10, desc: "利用地震的衝擊，攻擊自己周圍所有的寶可夢。" },
  { id: 90, name: "地裂", en: "Fissure", type: "地面", cat: "physical", bp: 0, acc: 0, pp: 5, desc: "讓對手掉落於地裂的裂縫中進行攻擊。只要命中就會一擊昏厥。" },
  { id: 91, name: "挖洞", en: "Dig", type: "地面", cat: "physical", bp: 80, acc: 100, pp: 10, desc: "第１回合鑽入地底，第２回合攻擊對手。" },
  { id: 92, name: "劇毒", en: "Toxic", type: "毒", cat: "status", bp: 0, acc: 90, pp: 10, desc: "讓對手陷入劇毒狀態。隨著回合的推進，中毒傷害會增加。" },
  { id: 93, name: "念力", en: "Confusion", type: "超能力", cat: "special", bp: 50, acc: 100, pp: 25, desc: "向對手發送微弱的念力進行攻擊。有時會使對手混亂。" },
  { id: 94, name: "精神強念", en: "Psychic", type: "超能力", cat: "special", bp: 90, acc: 100, pp: 10, desc: "向對手發送強大的念力進行攻擊。有時會降低對手的特防。" },
  { id: 95, name: "催眠術", en: "Hypnosis", type: "超能力", cat: "status", bp: 0, acc: 60, pp: 20, desc: "施以誘導睡意的暗示，讓對手陷入睡眠狀態。" },
  { id: 96, name: "瑜伽姿勢", en: "Meditate", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 40, desc: "喚醒身體深處沉睡的力量，從而提高自己的攻擊。" },
  { id: 97, name: "高速移動", en: "Agility", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 30, desc: "讓身體放鬆變得輕盈，以便高速移動。大幅提高自己的速度。" },
  { id: 98, name: "電光一閃", en: "Quick Attack", type: "一般", cat: "physical", bp: 40, acc: 100, pp: 30, desc: "以迅雷不及掩耳之勢撲向對手。必定能夠先制攻擊。" },
  { id: 99, name: "憤怒", en: "Rage", type: "一般", cat: "physical", bp: 20, acc: 100, pp: 20, desc: "如果在使出招式後受到攻擊的話，會因憤怒的力量而提高攻擊。" },
  { id: 100, name: "瞬間移動", en: "Teleport", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 20, desc: "當有後備寶可夢時使用，就可以進行替換。野生的寶可夢使用則會逃走。" },
  { id: 101, name: "黑夜魔影", en: "Night Shade", type: "幽靈", cat: "special", bp: 0, acc: 100, pp: 15, desc: "顯示恐怖幻影，只給予對手和自己等級相同的傷害。" },
  { id: 102, name: "模仿", en: "Mimic", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "可以將對手最後使用的招式，在戰鬥內變成自己的招式。" },
  { id: 103, name: "刺耳聲", en: "Screech", type: "一般", cat: "status", bp: 0, acc: 85, pp: 40, desc: "發出不由自主想要摀起耳朵的刺耳聲，從而大幅降低對手的防禦。" },
  { id: 104, name: "影子分身", en: "Double Team", type: "一般", cat: "status", bp: 0, acc: 0, pp: 15, desc: "通過快速移動來製造分身，擾亂對手，從而提高閃避率。" },
  { id: 105, name: "自我再生", en: "Recover", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "讓細胞再生，從而回復自己最大ＨＰ的一半。" },
  { id: 106, name: "變硬", en: "Harden", type: "一般", cat: "status", bp: 0, acc: 0, pp: 30, desc: "全身使勁，讓身體變硬，從而提高自己的防禦。" },
  { id: 107, name: "變小", en: "Minimize", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "蜷縮身體顯得很小，從而大幅提高自己的閃避率。" },
  { id: 108, name: "煙幕", en: "Smokescreen", type: "一般", cat: "status", bp: 0, acc: 100, pp: 20, desc: "向對手噴出煙或墨汁等，從而降低對手的命中率。" },
  { id: 109, name: "奇異之光", en: "Confuse Ray", type: "幽靈", cat: "status", bp: 0, acc: 100, pp: 10, desc: "顯示奇怪的光，擾亂對手。使對手混亂。" },
  { id: 110, name: "縮入殼中", en: "Withdraw", type: "水", cat: "status", bp: 0, acc: 0, pp: 40, desc: "縮入殼裡保護身體，從而提高自己的防禦。" },
  { id: 111, name: "變圓", en: "Defense Curl", type: "一般", cat: "status", bp: 0, acc: 0, pp: 40, desc: "將身體蜷曲變圓，從而提高自己的防禦。" },
  { id: 112, name: "屏障", en: "Barrier", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 20, desc: "製造堅固的壁障，從而大幅提高自己的防禦。" },
  { id: 113, name: "光牆", en: "Light Screen", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 30, desc: "利用神奇的牆壁，在５回合內減弱從對手那裡受到的特殊攻擊的傷害。" },
  { id: 114, name: "黑霧", en: "Haze", type: "冰", cat: "status", bp: 0, acc: 0, pp: 30, desc: "升起黑霧，將正在場上戰鬥的全體寶可夢的能力變回原點。" },
  { id: 115, name: "反射壁", en: "Reflect", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 20, desc: "利用神奇的牆壁，在５回合內減弱從對手那裡受到的物理攻擊的傷害。" },
  { id: 116, name: "聚氣", en: "Focus Energy", type: "一般", cat: "status", bp: 0, acc: 0, pp: 30, desc: "深深地吸口氣，集中精神。自己的攻擊會變得容易擊中要害。" },
  { id: 117, name: "忍耐", en: "Bide", type: "一般", cat: "physical", bp: 0, acc: 0, pp: 10, desc: "在２回合內忍受攻擊，受到的傷害會２倍返還給對手。" },
  { id: 118, name: "揮指", en: "Metronome", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "揮動手指刺激自己的大腦，從許多的招式中隨機使出１個。" },
  { id: 119, name: "鸚鵡學舌", en: "Mirror Move", type: "飛行", cat: "status", bp: 0, acc: 0, pp: 20, desc: "模仿對手使用的招式，自己也使用相同招式。" },
  { id: 120, name: "玉石俱碎", en: "Self-Destruct", type: "一般", cat: "physical", bp: 200, acc: 100, pp: 5, desc: "引發爆炸，攻擊自己周圍所有的寶可夢。使用後陷入昏厥。" },
  { id: 121, name: "炸蛋", en: "Egg Bomb", type: "一般", cat: "physical", bp: 100, acc: 75, pp: 10, desc: "向對手用力投擲大大的蛋進行攻擊。" },
  { id: 122, name: "舌舔", en: "Lick", type: "幽靈", cat: "physical", bp: 30, acc: 100, pp: 30, desc: "用長長的舌頭，舔遍對手進行攻擊。有時會讓對手陷入麻痺狀態。" },
  { id: 123, name: "濁霧", en: "Smog", type: "毒", cat: "special", bp: 30, acc: 70, pp: 20, desc: "將骯髒的濃霧吹向對手進行攻擊。有時會讓對手陷入中毒狀態。" },
  { id: 124, name: "污泥攻擊", en: "Sludge", type: "毒", cat: "special", bp: 65, acc: 100, pp: 20, desc: "用污泥投擲對手進行攻擊。有時會讓對手陷入中毒狀態。" },
  { id: 125, name: "骨棒", en: "Bone Club", type: "地面", cat: "physical", bp: 65, acc: 85, pp: 20, desc: "用手中的骨頭毆打對手進行攻擊。有時會使對手畏縮。" },
  { id: 126, name: "大字爆炎", en: "Fire Blast", type: "火", cat: "special", bp: 110, acc: 85, pp: 5, desc: "用大字形狀的火焰燒盡對手。有時會讓對手陷入灼傷狀態。" },
  { id: 127, name: "攀瀑", en: "Waterfall", type: "水", cat: "physical", bp: 80, acc: 100, pp: 15, desc: "以驚人的氣勢撲向對手。有時會使對手畏縮。" },
  { id: 128, name: "貝殼夾擊", en: "Clamp", type: "水", cat: "physical", bp: 35, acc: 85, pp: 15, desc: "用非常堅固且厚實的貝殼，在４～５回合內夾住對手進行攻擊。" },
  { id: 129, name: "高速星星", en: "Swift", type: "一般", cat: "special", bp: 60, acc: 0, pp: 20, desc: "發射星形的光攻擊對手。攻擊必定會命中。" },
  { id: 130, name: "火箭頭錘", en: "Skull Bash", type: "一般", cat: "physical", bp: 130, acc: 100, pp: 10, desc: "第１回合把頭縮進去，從而提高防禦。第２回合攻擊對手。" },
  { id: 131, name: "尖刺加農炮", en: "Spike Cannon", type: "一般", cat: "physical", bp: 20, acc: 100, pp: 15, desc: "向對手發射銳針進行攻擊。連續攻擊２～５次。" },
  { id: 132, name: "纏繞", en: "Constrict", type: "一般", cat: "physical", bp: 10, acc: 100, pp: 35, desc: "用觸手或青藤等纏繞進行攻擊。有時會降低對手的速度。" },
  { id: 133, name: "瞬間失憶", en: "Amnesia", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 20, desc: "將頭腦清空，瞬間忘記某事，從而大幅提高自己的特防。" },
  { id: 134, name: "折彎湯匙", en: "Kinesis", type: "超能力", cat: "status", bp: 0, acc: 80, pp: 15, desc: "折彎湯匙引開注意，從而降低對手的命中率。" },
  { id: 135, name: "生蛋", en: "Soft-Boiled", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "回復自己最大ＨＰ的一半。" },
  { id: 136, name: "飛膝踢", en: "High Jump Kick", type: "格鬥", cat: "physical", bp: 130, acc: 90, pp: 10, desc: "跳起後用膝蓋撞對手進行攻擊。如果撞偏則自己會受到傷害。" },
  { id: 137, name: "大蛇瞪眼", en: "Glare", type: "一般", cat: "status", bp: 0, acc: 100, pp: 30, desc: "用腹部的花紋使對手害怕，從而讓其陷入麻痺狀態。" },
  { id: 138, name: "食夢", en: "Dream Eater", type: "超能力", cat: "special", bp: 100, acc: 100, pp: 15, desc: "吃掉正在睡覺的對手的夢進行攻擊。回復對手所受到傷害的一半ＨＰ。" },
  { id: 139, name: "毒瓦斯", en: "Poison Gas", type: "毒", cat: "status", bp: 0, acc: 90, pp: 40, desc: "將毒瓦斯吹到對手的臉上，從而讓對手陷入中毒狀態。" },
  { id: 140, name: "投球", en: "Barrage", type: "一般", cat: "physical", bp: 15, acc: 85, pp: 20, desc: "向對手投擲圓形物體進行攻擊。連續攻擊２～５次。" },
  { id: 141, name: "汲取", en: "Leech Life", type: "蟲", cat: "physical", bp: 80, acc: 100, pp: 10, desc: "吸取血液攻擊對手。可以回復給予對手傷害的一半ＨＰ。" },
  { id: 142, name: "惡魔之吻", en: "Lovely Kiss", type: "一般", cat: "status", bp: 0, acc: 75, pp: 10, desc: "用恐怖的臉強吻對手。讓對手陷入睡眠狀態。" },
  { id: 143, name: "神鳥猛擊", en: "Sky Attack", type: "飛行", cat: "physical", bp: 140, acc: 90, pp: 5, desc: "第２回合攻擊對手。偶爾使對手畏縮。也容易擊中要害。" },
  { id: 144, name: "變身", en: "Transform", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "變身成對手寶可夢的樣子，能夠使用和對手完全相同的招式。" },
  { id: 145, name: "泡沫", en: "Bubble", type: "水", cat: "special", bp: 40, acc: 100, pp: 30, desc: "向對手用力吹起無數泡泡進行攻擊。有時會降低對手的速度。" },
  { id: 146, name: "迷昏拳", en: "Dizzy Punch", type: "一般", cat: "physical", bp: 70, acc: 100, pp: 10, desc: "有節奏地出拳攻擊對手。有時會使對手混亂。" },
  { id: 147, name: "蘑菇孢子", en: "Spore", type: "草", cat: "status", bp: 0, acc: 100, pp: 15, desc: "沙沙沙地撒滿具有催眠效果的孢子，從而讓對手陷入睡眠狀態。" },
  { id: 148, name: "閃光", en: "Flash", type: "一般", cat: "status", bp: 0, acc: 100, pp: 20, desc: "使出光芒，從而降低對手的命中率。也可在陰暗的洞窟裡照亮四周。" },
  { id: 149, name: "精神波", en: "Psywave", type: "超能力", cat: "special", bp: 0, acc: 100, pp: 15, desc: "向對手發射神奇的念波進行攻擊。每次使用，傷害都會改變。" },
  { id: 150, name: "躍起", en: "Splash", type: "一般", cat: "status", bp: 0, acc: 0, pp: 40, desc: "也不攻擊只是一蹦一蹦地跳，什麼都不會發生……" }
]);
