// 全 920 種招式資料庫 (繁體中文版 - 第 2 批: 151~300)[cite: 13]
window.MOVES_DB = window.MOVES_DB || [];
window.MOVES_DB = window.MOVES_DB.concat([
  { id: 151, name: "溶化", en: "Acid Armor", type: "毒", cat: "status", bp: 0, acc: 0, pp: 20, desc: "通過細胞的變化進行液化，從而大幅提高自己的防禦。" },
  { id: 152, name: "蟹鉗錘", en: "Crabhammer", type: "水", cat: "physical", bp: 100, acc: 90, pp: 10, desc: "用大鉗子敲打對手進行攻擊。容易擊中要害。" },
  { id: 153, name: "大爆炸", en: "Explosion", type: "一般", cat: "physical", bp: 250, acc: 100, pp: 5, desc: "引發大爆炸，攻擊自己周圍所有的寶可夢。使用後自己會陷入昏厥。" },
  { id: 154, name: "亂抓", en: "Fury Swipes", type: "一般", cat: "physical", bp: 18, acc: 80, pp: 15, desc: "用爪子或鐮刀等抓對手進行攻擊。連續攻擊２～５次。" },
  { id: 155, name: "骨頭迴力鏢", en: "Bonemerang", type: "地面", cat: "physical", bp: 50, acc: 90, pp: 10, desc: "用手中的骨頭投擲對手，來回連續２次給予傷害。" },
  { id: 156, name: "睡覺", en: "Rest", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 5, desc: "連續睡上２回合。回復自己的全部ＨＰ以及治癒所有異常狀態。" },
  { id: 157, name: "岩崩", en: "Rock Slide", type: "岩石", cat: "physical", bp: 75, acc: 90, pp: 10, desc: "將大岩石猛烈地撞向對手進行攻擊。有時會使對手畏縮。" },
  { id: 158, name: "終結門牙", en: "Hyper Fang", type: "一般", cat: "physical", bp: 80, acc: 90, pp: 15, desc: "用鋒利的門牙牢牢地咬住對手進行攻擊。有時會使對手畏縮。" },
  { id: 159, name: "稜角化", en: "Sharpen", type: "一般", cat: "status", bp: 0, acc: 0, pp: 30, desc: "增加身體的角，變得稜稜角角，從而提高自己的攻擊。" },
  { id: 160, name: "紋理", en: "Conversion", type: "一般", cat: "status", bp: 0, acc: 0, pp: 30, desc: "將自己的屬性轉換成和已學會的招式中第一個招式相同的屬性。" },
  { id: 161, name: "三重攻擊", en: "Tri Attack", type: "一般", cat: "special", bp: 80, acc: 100, pp: 10, desc: "用３種光線進行攻擊。有時會讓對手陷入麻痺、灼傷或冰凍的狀態。" },
  { id: 162, name: "憤怒門牙", en: "Super Fang", type: "一般", cat: "physical", bp: 0, acc: 90, pp: 10, desc: "用鋒利的門牙猛烈地咬住對手進行攻擊。對手的ＨＰ減半。" },
  { id: 163, name: "劈開", en: "Slash", type: "一般", cat: "physical", bp: 70, acc: 100, pp: 20, desc: "用爪子或鐮刀等劈開對手進行攻擊。容易擊中要害。" },
  { id: 164, name: "替身", en: "Substitute", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "削減少許自己的ＨＰ，製造分身。分身將成為自己的替身。" },
  { id: 165, name: "掙扎", en: "Struggle", type: "一般", cat: "physical", bp: 50, acc: 0, pp: 0, desc: "當自己的ＰＰ耗盡時，努力掙扎攻擊對手。自己也會受到少許傷害。" },
  { id: 166, name: "寫生", en: "Sketch", type: "一般", cat: "status", bp: 0, acc: 0, pp: 1, desc: "將對手使用的招式變成自己的招式。使用１次後寫生消失。" },
  { id: 167, name: "三連踢", en: "Triple Kick", type: "格鬥", cat: "physical", bp: 10, acc: 90, pp: 10, desc: "連續３次踢對手進行攻擊。每踢中一次，威力就會提高。" },
  { id: 168, name: "小偷", en: "Thief", type: "惡", cat: "physical", bp: 60, acc: 100, pp: 25, desc: "攻擊的同時盜取道具。當自己攜帶道具時，不會去盜取。" },
  { id: 169, name: "蛛網", en: "Spider Web", type: "蟲", cat: "status", bp: 0, acc: 0, pp: 10, desc: "將黏糊糊的細絲一層一層纏住對手，使其不能從戰鬥中逃走。" },
  { id: 170, name: "心之眼", en: "Mind Reader", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "用心感受對手的行動，下次攻擊必定會擊中對手。" },
  { id: 171, name: "惡夢", en: "Nightmare", type: "幽靈", cat: "status", bp: 0, acc: 100, pp: 15, desc: "讓在睡眠狀態下的對手做惡夢，每回合會緩緩減少HP。" },
  { id: 172, name: "火焰輪", en: "Flame Wheel", type: "火", cat: "physical", bp: 60, acc: 100, pp: 25, desc: "讓火焰覆蓋全身，猛撞向對手進行攻擊。有時會讓對手陷入灼傷狀態。" },
  { id: 173, name: "打鼾", en: "Snore", type: "一般", cat: "special", bp: 50, acc: 100, pp: 15, desc: "在自己睡覺時，發出噪音進行攻擊。有時會使對手畏縮。" },
  { id: 174, name: "咒術", en: "Curse", type: "幽靈", cat: "status", bp: 0, acc: 0, pp: 10, desc: "使用該招式的寶可夢，其屬性是幽靈屬性或其他屬性時，效果會不一樣。" },
  { id: 175, name: "抓狂", en: "Flail", type: "一般", cat: "physical", bp: 0, acc: 100, pp: 15, desc: "抓狂般亂打進行攻擊。自己的ＨＰ越少，招式的威力越大。" },
  { id: 176, name: "紋理２", en: "Conversion 2", type: "一般", cat: "status", bp: 0, acc: 0, pp: 30, desc: "為了可以抵抗對手最後使用的招式，從而使自己的屬性發生變化。" },
  { id: 177, name: "氣旋攻擊", en: "Aeroblast", type: "飛行", cat: "special", bp: 100, acc: 95, pp: 5, desc: "發射空氣旋渦進行攻擊。容易擊中要害。" },
  { id: 178, name: "棉孢子", en: "Cotton Spore", type: "草", cat: "status", bp: 0, acc: 100, pp: 40, desc: "將棉花般柔軟的孢子緊貼對手，從而大幅降低對手的速度。" },
  { id: 179, name: "絕處逢生", en: "Reversal", type: "格鬥", cat: "physical", bp: 0, acc: 100, pp: 15, desc: "竭盡全力進行攻擊。自己的ＨＰ越少，招式的威力越大。" },
  { id: 180, name: "怨恨", en: "Spite", type: "幽靈", cat: "status", bp: 0, acc: 100, pp: 10, desc: "對對手最後使用的招式懷有怨恨，減少４ＰＰ該招式。" },
  { id: 181, name: "細雪", en: "Powder Snow", type: "冰", cat: "special", bp: 40, acc: 100, pp: 25, desc: "將冰冷的細雪吹向對手進行攻擊。有時會讓對手陷入冰凍狀態。" },
  { id: 182, name: "守住", en: "Protect", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "完全抵擋對手的攻擊。連續使出則容易失敗。" },
  { id: 183, name: "音速拳", en: "Mach Punch", type: "格鬥", cat: "physical", bp: 40, acc: 100, pp: 30, desc: "以迅雷不及掩耳之勢出拳。必定能夠先制攻擊。" },
  { id: 184, name: "可怕面孔", en: "Scary Face", type: "一般", cat: "status", bp: 0, acc: 100, pp: 10, desc: "用恐怖的表情瞪著對手，使其害怕，從而大幅降低對手的速度。" },
  { id: 185, name: "出奇一擊", en: "Feint Attack", type: "惡", cat: "physical", bp: 60, acc: 0, pp: 20, desc: "悄悄地靠近對手，趁其不備進行毆打。攻擊必定會命中。" },
  { id: 186, name: "天使之吻", en: "Sweet Kiss", type: "妖精", cat: "status", bp: 0, acc: 75, pp: 10, desc: "像天使般可愛地親吻對手，從而使對手混亂。" },
  { id: 187, name: "腹鼓", en: "Belly Drum", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "將自己的ＨＰ減少到最大ＨＰ的一半，從而最大限度提高自己的攻擊。" },
  { id: 188, name: "污泥炸彈", en: "Sludge Bomb", type: "毒", cat: "special", bp: 90, acc: 100, pp: 10, desc: "用污泥投擲對手進行攻擊。有時會讓對手陷入中毒狀態。" },
  { id: 189, name: "擲泥", en: "Mud-Slap", type: "地面", cat: "special", bp: 20, acc: 100, pp: 10, desc: "向對手的臉等投擲泥塊進行攻擊。會降低對手的命中率。" },
  { id: 190, name: "章魚桶炮", en: "Octazooka", type: "水", cat: "special", bp: 65, acc: 85, pp: 10, desc: "向對手的臉等噴出墨汁進行攻擊。有時會降低對手的命中率。" },
  { id: 191, name: "撒菱", en: "Spikes", type: "地面", cat: "status", bp: 0, acc: 0, pp: 20, desc: "在對手的腳下扔撒菱。對替換出場的對手的寶可夢給予傷害。" },
  { id: 192, name: "電磁炮", en: "Zap Cannon", type: "電", cat: "special", bp: 120, acc: 50, pp: 5, desc: "發射大炮一樣的電流進行攻擊。讓對手陷入麻痺狀態。" },
  { id: 193, name: "識破", en: "Foresight", type: "一般", cat: "status", bp: 0, acc: 0, pp: 40, desc: "使出後對幽靈屬性寶可夢沒有效果的招式以及閃避率高的對手，變得能夠打中。" },
  { id: 194, name: "同命", en: "Destiny Bond", type: "幽靈", cat: "status", bp: 0, acc: 0, pp: 5, desc: "使出招式後，當受到對手攻擊陷入昏厥時，對手也會一同昏厥。連續使出則會失敗。" },
  { id: 195, name: "滅亡之歌", en: "Perish Song", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "傾聽歌聲的寶可夢經過３回合陷入昏厥。替換後效果消失。" },
  { id: 196, name: "冰凍之風", en: "Icy Wind", type: "冰", cat: "special", bp: 55, acc: 95, pp: 15, desc: "將結冰的冷氣吹向對手進行攻擊。會降低對手的速度。" },
  { id: 197, name: "看穿", en: "Detect", type: "格鬥", cat: "status", bp: 0, acc: 0, pp: 5, desc: "完全抵擋對手的攻擊。連續使出則容易失敗。" },
  { id: 198, name: "骨棒亂打", en: "Bone Rush", type: "地面", cat: "physical", bp: 25, acc: 90, pp: 10, desc: "用堅硬的骨頭毆打對手進行攻擊。連續攻擊２～５次。" },
  { id: 199, name: "鎖定", en: "Lock-On", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "緊緊瞄準對手，下次攻擊必定會打中。" },
  { id: 200, name: "逆鱗", en: "Outrage", type: "龍", cat: "physical", bp: 120, acc: 100, pp: 10, desc: "在２～３回合內，亂打一氣地進行攻擊。大鬧一番後自己會陷入混亂。" },
  { id: 201, name: "沙暴", en: "Sandstorm", type: "岩石", cat: "status", bp: 0, acc: 0, pp: 10, desc: "在５回合內揚起沙暴，除岩石、地面和鋼屬性以外的寶可夢，都會受到傷害。岩石屬性的特防還會提高。" },
  { id: 202, name: "終極吸取", en: "Giga Drain", type: "草", cat: "special", bp: 75, acc: 100, pp: 10, desc: "吸取對手的養分進行攻擊。可以回復給予對手傷害的一半ＨＰ。" },
  { id: 203, name: "挺住", en: "Endure", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "即使受到攻擊，也至少會留下１ＨＰ。連續使出則容易失敗。" },
  { id: 204, name: "撒嬌", en: "Charm", type: "妖精", cat: "status", bp: 0, acc: 100, pp: 20, desc: "可愛地凝視，誘使對手疏忽大意，從而大幅降低對手的攻擊。" },
  { id: 205, name: "滾動", en: "Rollout", type: "岩石", cat: "physical", bp: 30, acc: 90, pp: 20, desc: "在５回合內連續滾動攻擊對手。招式每次擊中，威力就會提高。" },
  { id: 206, name: "點到為止", en: "False Swipe", type: "一般", cat: "physical", bp: 40, acc: 100, pp: 40, desc: "對手的ＨＰ至少會留下１ＨＰ，如此般手下留情地攻擊。" },
  { id: 207, name: "虛張聲勢", en: "Swagger", type: "一般", cat: "status", bp: 0, acc: 85, pp: 15, desc: "激怒對手，使其混亂。因為憤怒，對手的攻擊會大幅提高。" },
  { id: 208, name: "喝牛奶", en: "Milk Drink", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "回復自己最大ＨＰ的一半。" },
  { id: 209, name: "電光", en: "Spark", type: "電", cat: "physical", bp: 65, acc: 100, pp: 20, desc: "讓電流覆蓋全身，猛撞向對手進行攻擊。有時會讓對手陷入麻痺狀態。" },
  { id: 210, name: "連斬", en: "Fury Cutter", type: "蟲", cat: "physical", bp: 40, acc: 95, pp: 20, desc: "用鐮刀或爪子等切斬對手進行攻擊。連續擊中，威力就會提高。" },
  { id: 211, name: "鋼翼", en: "Steel Wing", type: "鋼", cat: "physical", bp: 70, acc: 90, pp: 25, desc: "用堅硬的翅膀敲打對手進行攻擊。有時會提高自己的防禦。" },
  { id: 212, name: "黑色目光", en: "Mean Look", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "用好似要勾人心魂的黑色目光一動不動地凝視對手，使其不能從戰鬥中逃走。" },
  { id: 213, name: "迷人", en: "Attract", type: "一般", cat: "status", bp: 0, acc: 100, pp: 15, desc: "♂誘惑♀或♀誘惑♂，讓對手著迷。對手將很難使出招式。" },
  { id: 214, name: "夢話", en: "Sleep Talk", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "從自己已學會的招式中任意使出１個。只能在自己睡覺時使用。" },
  { id: 215, name: "治癒鈴聲", en: "Heal Bell", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "讓同伴聽舒適的鈴音，從而治癒我方全員的異常狀態。" },
  { id: 216, name: "報恩", en: "Return", type: "一般", cat: "physical", bp: 0, acc: 100, pp: 20, desc: "為了訓練家而全力攻擊對手。親密度越高，威力越大。" },
  { id: 217, name: "禮物", en: "Present", type: "一般", cat: "physical", bp: 0, acc: 90, pp: 15, desc: "遞給對手設有圈套的盒子進行攻擊。也有可能回復對手ＨＰ。" },
  { id: 218, name: "遷怒", en: "Frustration", type: "一般", cat: "physical", bp: 0, acc: 100, pp: 20, desc: "為了發洩不滿而全力攻擊對手。親密度越低，威力越大。" },
  { id: 219, name: "神秘守護", en: "Safeguard", type: "一般", cat: "status", bp: 0, acc: 0, pp: 25, desc: "在５回合內被神奇的力量守護，從而不會陷入異常狀態。" },
  { id: 220, name: "分擔痛楚", en: "Pain Split", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "將自己的ＨＰ和對手的ＨＰ相加，然後自己和對手友好地平分。" },
  { id: 221, name: "神聖之火", en: "Sacred Fire", type: "火", cat: "physical", bp: 100, acc: 95, pp: 5, desc: "用神秘的火焰燒盡對手進行攻擊。有時會讓對手陷入灼傷狀態。" },
  { id: 222, name: "震級", en: "Magnitude", type: "地面", cat: "physical", bp: 0, acc: 100, pp: 30, desc: "晃動地面，攻擊自己周圍所有的寶可夢。招式的威力會有各種變化。" },
  { id: 223, name: "爆裂拳", en: "Dynamic Punch", type: "格鬥", cat: "physical", bp: 100, acc: 50, pp: 5, desc: "使出渾身力氣出拳進行攻擊。必定會使對手混亂。" },
  { id: 224, name: "超級角擊", en: "Megahorn", type: "蟲", cat: "physical", bp: 120, acc: 85, pp: 10, desc: "用堅硬且華麗的角狠狠地刺入對手進行攻擊。" },
  { id: 225, name: "龍息", en: "Dragon Breath", type: "龍", cat: "special", bp: 60, acc: 100, pp: 20, desc: "將強烈的氣息吹向對手進行攻擊。有時會讓對手陷入麻痺狀態。" },
  { id: 226, name: "接棒", en: "Baton Pass", type: "一般", cat: "status", bp: 0, acc: 0, pp: 40, desc: "和後備寶可夢進行替換。換上的寶可夢能直接繼承其能力的變化。" },
  { id: 227, name: "再來一次", en: "Encore", type: "一般", cat: "status", bp: 0, acc: 100, pp: 5, desc: "讓對手接受再來一次，連續３次使出最後使用的招式。" },
  { id: 228, name: "追打", en: "Pursuit", type: "惡", cat: "physical", bp: 40, acc: 100, pp: 20, desc: "當對手替換寶可夢上場時使出此招式的話，能夠以２倍的威力進行攻擊。" },
  { id: 229, name: "高速旋轉", en: "Rapid Spin", type: "一般", cat: "physical", bp: 50, acc: 100, pp: 40, desc: "通過旋轉來攻擊對手。可以擺脫綁緊、緊束、寄生種子等招式。還能提高自己的速度。" },
  { id: 230, name: "甜甜香氣", en: "Sweet Scent", type: "一般", cat: "status", bp: 0, acc: 100, pp: 20, desc: "用香氣大幅降低對手的閃避率。" },
  { id: 231, name: "鐵尾", en: "Iron Tail", type: "鋼", cat: "physical", bp: 100, acc: 75, pp: 15, desc: "使用堅硬的尾巴摔打對手進行攻擊。有時會降低對手的防禦。" },
  { id: 232, name: "金屬爪", en: "Metal Claw", type: "鋼", cat: "physical", bp: 50, acc: 95, pp: 35, desc: "用鋼鐵之爪劈開對手進行攻擊。有時會提高自己的攻擊。" },
  { id: 233, name: "借力摔", en: "Vital Throw", type: "格鬥", cat: "physical", bp: 70, acc: 0, pp: 10, desc: "會在對手之後進行攻擊。但是自己的攻擊必定會命中。" },
  { id: 234, name: "晨光", en: "Morning Sun", type: "一般", cat: "status", bp: 0, acc: 0, pp: 5, desc: "回復自己的ＨＰ。根據天氣的不同，回復量也會有所變化。" },
  { id: 235, name: "光合作用", en: "Synthesis", type: "草", cat: "status", bp: 0, acc: 0, pp: 5, desc: "回復自己的ＨＰ。根據天氣的不同，回復量也會有所變化。" },
  { id: 236, name: "月光", en: "Moonlight", type: "妖精", cat: "status", bp: 0, acc: 0, pp: 5, desc: "回復自己的ＨＰ。根據天氣的不同，回復量也會有所變化。" },
  { id: 237, name: "覺醒力量", en: "Hidden Power", type: "一般", cat: "special", bp: 60, acc: 100, pp: 15, desc: "招式的屬性會隨著使用此招式的寶可夢而改變。" },
  { id: 238, name: "十字劈", en: "Cross Chop", type: "格鬥", cat: "physical", bp: 100, acc: 80, pp: 5, desc: "用兩手呈十字劈打對手進行攻擊。容易擊中要害。" },
  { id: 239, name: "龍捲風", en: "Twister", type: "龍", cat: "special", bp: 40, acc: 100, pp: 20, desc: "興起龍捲風，將對手捲入進行攻擊。有時會使對手畏縮。" },
  { id: 240, name: "求雨", en: "Rain Dance", type: "水", cat: "status", bp: 0, acc: 0, pp: 5, desc: "在５回合內一直降雨，從而提高水屬性的招式威力。火屬性的招式威力則降低。" },
  { id: 241, name: "大晴天", en: "Sunny Day", type: "火", cat: "status", bp: 0, acc: 0, pp: 5, desc: "在５回合內讓日照變得強烈，從而提高火屬性的招式威力。水屬性的招式威力則降低。" },
  { id: 242, name: "咬碎", en: "Crunch", type: "惡", cat: "physical", bp: 80, acc: 100, pp: 15, desc: "用利牙咬碎對手進行攻擊。有時會降低對手的防禦。" },
  { id: 243, name: "鏡面反射", en: "Mirror Coat", type: "超能力", cat: "special", bp: 0, acc: 100, pp: 20, desc: "從對手那裡受到特殊攻擊的傷害將以２倍返還給同一個對手。" },
  { id: 244, name: "自我暗示", en: "Psych Up", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "向自己施以自我暗示，將能力變化的狀態變得和對手一樣。" },
  { id: 245, name: "神速", en: "Extreme Speed", type: "一般", cat: "physical", bp: 80, acc: 100, pp: 5, desc: "以迅雷不及掩耳之勢猛撞向對手進行攻擊。必定能夠先制攻擊。" },
  { id: 246, name: "原始之力", en: "Ancient Power", type: "岩石", cat: "special", bp: 60, acc: 100, pp: 5, desc: "用原始之力進行攻擊。有時會提高自己所有的能力。" },
  { id: 247, name: "暗影球", en: "Shadow Ball", type: "幽靈", cat: "special", bp: 80, acc: 100, pp: 15, desc: "投擲一團黑影進行攻擊。有時會降低對手的特防。" },
  { id: 248, name: "預知未來", en: "Future Sight", type: "超能力", cat: "special", bp: 120, acc: 100, pp: 10, desc: "在使用招式２回合後，向對手發送一團念力進行攻擊。" },
  { id: 249, name: "碎岩", en: "Rock Smash", type: "格鬥", cat: "physical", bp: 40, acc: 100, pp: 15, desc: "用拳頭進行攻擊。有時會降低對手的防禦。" },
  { id: 250, name: "潮旋", en: "Whirlpool", type: "水", cat: "special", bp: 35, acc: 85, pp: 15, desc: "將對手困在激烈的水流旋渦中，在４～５回合內進行攻擊。" },
  { id: 251, name: "圍攻", en: "Beat Up", type: "惡", cat: "physical", bp: 0, acc: 100, pp: 10, desc: "我方全員進行攻擊。同行的寶可夢越多，招式的攻擊次數越多。" },
  { id: 252, name: "擊掌奇襲", en: "Fake Out", type: "一般", cat: "physical", bp: 40, acc: 100, pp: 10, desc: "進行先制攻擊，使對手畏縮。要在出場後立刻使出才能成功。" },
  { id: 253, name: "吵鬧", en: "Uproar", type: "一般", cat: "special", bp: 90, acc: 100, pp: 10, desc: "在３回合內大吵大鬧攻擊對手。在此期間誰都不能入眠。" },
  { id: 254, name: "蓄力", en: "Stockpile", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "積蓄力量，提高自己的防禦和特防。最多積蓄３次。" },
  { id: 255, name: "噴出", en: "Spit Up", type: "一般", cat: "special", bp: 0, acc: 100, pp: 10, desc: "將積蓄的力量撞向對手進行攻擊。積蓄得越多，威力越大。" },
  { id: 256, name: "吞下", en: "Swallow", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "將積蓄的力量吞下，從而回復自己的ＨＰ。積蓄得越多，回復越大。" },
  { id: 257, name: "熱風", en: "Heat Wave", type: "火", cat: "special", bp: 95, acc: 90, pp: 10, desc: "將炎熱的氣息吹向對手進行攻擊。有時會讓對手陷入灼傷狀態。" },
  { id: 258, name: "冰雹", en: "Hail", type: "冰", cat: "status", bp: 0, acc: 0, pp: 10, desc: "在５回合內一直降冰雹，除冰屬性的寶可夢以外，給予全體寶可夢傷害。" },
  { id: 259, name: "無理取鬧", en: "Torment", type: "惡", cat: "status", bp: 0, acc: 100, pp: 15, desc: "向對手無理取鬧，令其不能連續２次使出相同招式。" },
  { id: 260, name: "吹捧", en: "Flatter", type: "惡", cat: "status", bp: 0, acc: 100, pp: 15, desc: "吹捧對手，使其混亂。同時還會提高對手的特攻。" },
  { id: 261, name: "鬼火", en: "Will-O-Wisp", type: "火", cat: "status", bp: 0, acc: 85, pp: 15, desc: "放出怪異的火焰，從而讓對手陷入灼傷狀態。" },
  { id: 262, name: "臨別禮物", en: "Memento", type: "惡", cat: "status", bp: 0, acc: 100, pp: 10, desc: "雖然會使自己陷入昏厥，但是能夠大幅降低對手的攻擊和特攻。" },
  { id: 263, name: "硬撐", en: "Facade", type: "一般", cat: "physical", bp: 70, acc: 100, pp: 20, desc: "當自己處於中毒、麻痺、灼傷狀態時，向對手使出此招式的話，威力會變成２倍。" },
  { id: 264, name: "真氣拳", en: "Focus Punch", type: "格鬥", cat: "physical", bp: 150, acc: 100, pp: 20, desc: "集中精神出拳。在招式使出前若受到攻擊則會失敗。" },
  { id: 265, name: "清醒", en: "Smelling Salts", type: "一般", cat: "physical", bp: 70, acc: 100, pp: 10, desc: "對於麻痺狀態下的對手，威力會變成２倍。但相反對手的麻痺也會被治癒。" },
  { id: 266, name: "看我嘛", en: "Follow Me", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "引起對手的注意，將對手的攻擊全部轉移到自己身上。" },
  { id: 267, name: "自然之力", en: "Nature Power", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "用自然之力進行攻擊。根據所使用場所的不同，使出的招式也會有所變化。" },
  { id: 268, name: "充電", en: "Charge", type: "電", cat: "status", bp: 0, acc: 0, pp: 20, desc: "變為充電狀態，提高下次使出的電屬性的招式威力。自己的特防也會提高。" },
  { id: 269, name: "挑釁", en: "Taunt", type: "惡", cat: "status", bp: 0, acc: 100, pp: 20, desc: "使對手憤怒。在３回合內讓對手只能使出給予傷害的招式。" },
  { id: 270, name: "幫助", en: "Helping Hand", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "幫助夥伴。被幫助的寶可夢，其招式威力變得比平時大。" },
  { id: 271, name: "戲法", en: "Trick", type: "超能力", cat: "status", bp: 0, acc: 100, pp: 10, desc: "抓住對手的空隙，交換自己和對手的持有物。" },
  { id: 272, name: "扮演", en: "Role Play", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 10, desc: "扮演對手，讓自己的特性變得和對手相同。" },
  { id: 273, name: "祈願", en: "Wish", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "在下一回合回復自己或是替換出場的寶可夢最大ＨＰ的一半。" },
  { id: 274, name: "借助", en: "Assist", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "向同伴緊急求助，從我方寶可夢已學會的招式中隨機使用１個。" },
  { id: 275, name: "紮根", en: "Ingrain", type: "草", cat: "status", bp: 0, acc: 0, pp: 20, desc: "在大地上紮根，每回合回復自己的ＨＰ。因為紮根了，所以不能替換寶可夢。" },
  { id: 276, name: "蠻力", en: "Superpower", type: "格鬥", cat: "physical", bp: 120, acc: 100, pp: 5, desc: "發揮驚人的力量攻擊對手。自己的攻擊和防禦會降低。" },
  { id: 277, name: "魔法反射", en: "Magic Coat", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 15, desc: "當對手使出會變成異常狀態的招式或寄生種子等時，會將對手的招式反射回去。" },
  { id: 278, name: "回收利用", en: "Recycle", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "使戰鬥中已經消耗掉的自己的持有物再生，並可以再次使用。" },
  { id: 279, name: "報復", en: "Revenge", type: "格鬥", cat: "physical", bp: 60, acc: 100, pp: 10, desc: "如果受到對手的招式攻擊，就能給予對手２倍的傷害。" },
  { id: 280, name: "劈瓦", en: "Brick Break", type: "格鬥", cat: "physical", bp: 75, acc: 100, pp: 15, desc: "將手刀猛烈地揮下攻擊對手。還可以破壞光牆和反射壁等。" },
  { id: 281, name: "哈欠", en: "Yawn", type: "一般", cat: "status", bp: 0, acc: 0, pp: 10, desc: "打個大哈欠引起睡意。在下一回合讓對手陷入睡眠狀態。" },
  { id: 282, name: "拍落", en: "Knock Off", type: "惡", cat: "physical", bp: 65, acc: 100, pp: 20, desc: "拍落對手的持有物，直到戰鬥結束都不能使用。對手攜帶道具時會增加傷害。" },
  { id: 283, name: "蠻幹", en: "Endeavor", type: "一般", cat: "physical", bp: 0, acc: 100, pp: 5, desc: "給予傷害，使對手的ＨＰ變得和自己的ＨＰ一樣。" },
  { id: 284, name: "噴火", en: "Eruption", type: "火", cat: "special", bp: 150, acc: 100, pp: 5, desc: "爆發怒火攻擊對手。自己的ＨＰ越少，招式的威力越小。" },
  { id: 285, name: "特性互換", en: "Skill Swap", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 10, desc: "利用超能力互換自己和對手的特性。" },
  { id: 286, name: "封印", en: "Imprison", type: "超能力", cat: "status", bp: 0, acc: 0, pp: 10, desc: "如果對手有和自己相同的招式，那麼只有對手無法使用該招式。" },
  { id: 287, name: "煥然一新", en: "Refresh", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "讓身體休息，治癒自己身上所中的毒、麻痺、灼傷的異常狀態。" },
  { id: 288, name: "怨念", en: "Grudge", type: "幽靈", cat: "status", bp: 0, acc: 0, pp: 5, desc: "因對手的招式而陷入昏厥時給對手施加怨念，讓該招式的ＰＰ變成０。" },
  { id: 289, name: "化為己用", en: "Snatch", type: "惡", cat: "status", bp: 0, acc: 0, pp: 10, desc: "將對手打算使用的回復招式或能力變化招式奪為己用。" },
  { id: 290, name: "秘密之力", en: "Secret Power", type: "一般", cat: "physical", bp: 70, acc: 100, pp: 20, desc: "根據使用場所不同，該招式的追加效果也會有所變化。" },
  { id: 291, name: "潛水", en: "Dive", type: "水", cat: "physical", bp: 80, acc: 100, pp: 10, desc: "第１回合潛入水中，第２回合浮上來進行攻擊。" },
  { id: 292, name: "猛推", en: "Arm Thrust", type: "格鬥", cat: "physical", bp: 15, acc: 100, pp: 20, desc: "用張開著的雙手猛推對手進行攻擊。連續攻擊２～５次。" },
  { id: 293, name: "保護色", en: "Camouflage", type: "一般", cat: "status", bp: 0, acc: 0, pp: 20, desc: "根據所在場所不同，如水邊、草叢和洞窟等，可以改變自己的屬性。" },
  { id: 294, name: "螢火", en: "Tail Glow", type: "蟲", cat: "status", bp: 0, acc: 0, pp: 20, desc: "凝視閃爍的光芒，集中自己的精神，從而巨幅提高特攻。" },
  { id: 295, name: "潔淨光芒", en: "Luster Purge", type: "超能力", cat: "special", bp: 95, acc: 100, pp: 5, desc: "釋放耀眼的光芒進行攻擊。有時會降低對手的特防。" },
  { id: 296, name: "薄霧球", en: "Mist Ball", type: "超能力", cat: "special", bp: 95, acc: 100, pp: 5, desc: "用圍繞著霧狀羽毛的球進行攻擊。有時會降低對手的特攻。" },
  { id: 297, name: "羽毛舞", en: "Feather Dance", type: "飛行", cat: "status", bp: 0, acc: 100, pp: 15, desc: "撒出羽毛，籠罩在對手的周圍。大幅降低對手的攻擊。" },
  { id: 298, name: "搖晃舞", en: "Teeter Dance", type: "一般", cat: "status", bp: 0, acc: 100, pp: 20, desc: "搖搖晃晃地跳起舞蹈，讓自己周圍的寶可夢陷入混亂狀態。" },
  { id: 299, name: "火焰踢", en: "Blaze Kick", type: "火", cat: "physical", bp: 85, acc: 90, pp: 10, desc: "攻擊對手後，有時會使其陷入灼傷狀態。也容易擊中要害。" },
  { id: 300, name: "玩泥巴", en: "Mud Sport", type: "地面", cat: "status", bp: 0, acc: 0, pp: 15, desc: "一旦使用此招式，周圍就會弄得到處是泥。在５回合內減弱電屬性的招式。" }
]);
